// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module toe_top_finalize_ipv4_checksum_32_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        txEng_subChecksumsFifo_dout,
        txEng_subChecksumsFifo_empty_n,
        txEng_subChecksumsFifo_read,
        txEng_tcpChecksumFifo_din,
        txEng_tcpChecksumFifo_full_n,
        txEng_tcpChecksumFifo_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [1023:0] txEng_subChecksumsFifo_dout;
input   txEng_subChecksumsFifo_empty_n;
output   txEng_subChecksumsFifo_read;
output  [15:0] txEng_tcpChecksumFifo_din;
input   txEng_tcpChecksumFifo_full_n;
output   txEng_tcpChecksumFifo_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg txEng_subChecksumsFifo_read;
reg txEng_tcpChecksumFifo_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire   [0:0] tmp_i_nbreadreq_fu_290_p3;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
reg   [0:0] tmp_i_reg_2859;
reg   [0:0] tmp_i_reg_2859_pp0_iter3_reg;
reg    ap_block_state5_pp0_stage0_iter4;
reg    ap_block_pp0_stage0_11001;
reg    txEng_subChecksumsFifo_blk_n;
wire    ap_block_pp0_stage0;
reg    txEng_tcpChecksumFifo_blk_n;
reg   [0:0] tmp_i_reg_2859_pp0_iter1_reg;
reg   [0:0] tmp_i_reg_2859_pp0_iter2_reg;
reg   [7:0] trunc_ln145_s_reg_2863;
reg   [7:0] trunc_ln145_65_reg_2868;
reg   [7:0] trunc_ln145_66_reg_2873;
reg   [7:0] trunc_ln145_67_reg_2878;
reg   [7:0] trunc_ln145_68_reg_2883;
reg   [7:0] trunc_ln145_69_reg_2888;
reg   [7:0] trunc_ln145_70_reg_2893;
reg   [7:0] trunc_ln145_71_reg_2898;
reg   [7:0] trunc_ln145_72_reg_2903;
reg   [7:0] trunc_ln145_73_reg_2908;
reg   [7:0] trunc_ln145_74_reg_2913;
reg   [7:0] trunc_ln145_75_reg_2918;
reg   [7:0] trunc_ln145_76_reg_2923;
reg   [7:0] trunc_ln145_77_reg_2928;
reg   [7:0] trunc_ln145_78_reg_2933;
reg   [7:0] trunc_ln145_80_reg_2938;
reg   [7:0] trunc_ln145_81_reg_2943;
reg   [7:0] trunc_ln145_82_reg_2948;
reg   [7:0] trunc_ln145_83_reg_2953;
reg   [7:0] trunc_ln145_84_reg_2958;
reg   [7:0] trunc_ln145_85_reg_2963;
reg   [7:0] trunc_ln145_86_reg_2968;
reg   [7:0] trunc_ln145_87_reg_2973;
reg   [7:0] trunc_ln145_88_reg_2978;
reg   [7:0] trunc_ln145_89_reg_2983;
reg   [7:0] trunc_ln145_90_reg_2988;
reg   [7:0] trunc_ln145_91_reg_2993;
wire   [7:0] trunc_ln691_fu_625_p1;
reg   [7:0] trunc_ln691_reg_2998;
reg   [7:0] trunc_ln691_s_reg_3003;
wire   [15:0] trunc_ln691_69_fu_639_p1;
reg   [15:0] trunc_ln691_69_reg_3008;
reg   [15:0] trunc_ln691_7_reg_3013;
reg   [0:0] tmp_311_reg_3018;
reg   [15:0] or_ln691_52_reg_3024;
reg   [7:0] trunc_ln691_8_reg_3029;
reg   [15:0] trunc_ln691_9_reg_3034;
reg   [0:0] tmp_312_reg_3039;
reg   [15:0] or_ln2_reg_3045;
reg   [7:0] trunc_ln691_10_reg_3050;
reg   [15:0] trunc_ln691_11_reg_3055;
reg   [0:0] tmp_313_reg_3060;
reg   [15:0] or_ln691_53_reg_3066;
reg   [7:0] trunc_ln691_12_reg_3071;
reg   [15:0] trunc_ln691_13_reg_3076;
reg   [0:0] tmp_314_reg_3081;
reg   [15:0] or_ln691_54_reg_3087;
reg   [15:0] or_ln691_55_reg_3092;
reg   [0:0] tmp_315_reg_3097;
reg   [15:0] or_ln691_56_reg_3103;
reg   [15:0] or_ln691_57_reg_3108;
reg   [0:0] tmp_316_reg_3113;
reg   [15:0] or_ln691_58_reg_3119;
reg   [15:0] or_ln691_59_reg_3124;
reg   [0:0] tmp_317_reg_3129;
reg   [15:0] or_ln691_60_reg_3135;
reg   [15:0] or_ln691_61_reg_3140;
reg   [0:0] tmp_318_reg_3145;
reg   [15:0] or_ln691_62_reg_3151;
reg   [15:0] or_ln691_63_reg_3156;
reg   [0:0] tmp_319_reg_3161;
reg   [15:0] or_ln691_64_reg_3167;
reg   [15:0] or_ln691_65_reg_3172;
reg   [0:0] tmp_320_reg_3177;
reg   [15:0] or_ln691_66_reg_3183;
reg   [15:0] or_ln691_67_reg_3188;
reg   [0:0] tmp_321_reg_3193;
reg   [15:0] or_ln691_68_reg_3199;
reg   [15:0] or_ln691_69_reg_3204;
reg   [0:0] tmp_322_reg_3209;
reg   [15:0] or_ln691_70_reg_3215;
reg   [15:0] or_ln691_71_reg_3220;
reg   [0:0] tmp_323_reg_3225;
reg   [15:0] or_ln691_72_reg_3231;
reg   [15:0] or_ln691_73_reg_3236;
reg   [0:0] tmp_324_reg_3241;
reg   [15:0] or_ln691_74_reg_3247;
reg   [15:0] or_ln691_75_reg_3252;
reg   [0:0] tmp_325_reg_3257;
reg   [15:0] or_ln691_76_reg_3263;
reg   [15:0] or_ln691_77_reg_3268;
reg   [0:0] tmp_326_reg_3273;
wire   [7:0] add_ln497_fu_1498_p2;
reg   [7:0] add_ln497_reg_3279;
wire   [7:0] add_ln497_1_fu_1534_p2;
reg   [7:0] add_ln497_1_reg_3284;
wire   [7:0] add_ln497_2_fu_1570_p2;
reg   [7:0] add_ln497_2_reg_3289;
wire   [7:0] add_ln497_3_fu_1606_p2;
reg   [7:0] add_ln497_3_reg_3294;
wire   [7:0] add_ln497_8_fu_1786_p2;
reg   [7:0] add_ln497_8_reg_3299;
wire   [7:0] add_ln497_9_fu_1822_p2;
reg   [7:0] add_ln497_9_reg_3304;
wire   [7:0] add_ln497_10_fu_1858_p2;
reg   [7:0] add_ln497_10_reg_3309;
wire   [7:0] add_ln497_11_fu_1894_p2;
reg   [7:0] add_ln497_11_reg_3314;
wire   [0:0] tmp_327_fu_2083_p3;
reg   [0:0] tmp_327_reg_3319;
reg   [7:0] trunc_ln1_reg_3324;
wire   [0:0] tmp_328_fu_2147_p3;
reg   [0:0] tmp_328_reg_3329;
reg   [7:0] trunc_ln507_1_reg_3334;
wire   [0:0] tmp_329_fu_2211_p3;
reg   [0:0] tmp_329_reg_3339;
reg   [7:0] trunc_ln507_2_reg_3344;
wire   [0:0] tmp_330_fu_2275_p3;
reg   [0:0] tmp_330_reg_3349;
reg   [7:0] trunc_ln507_3_reg_3354;
wire   [15:0] add_ln213_224_fu_2357_p2;
reg   [15:0] add_ln213_224_reg_3359;
wire   [15:0] add_ln213_225_fu_2411_p2;
reg   [15:0] add_ln213_225_reg_3365;
wire   [15:0] add_ln213_226_fu_2465_p2;
reg   [15:0] add_ln213_226_reg_3371;
wire   [15:0] add_ln213_227_fu_2519_p2;
reg   [15:0] add_ln213_227_reg_3377;
wire   [15:0] add_ln213_228_fu_2623_p2;
reg   [15:0] add_ln213_228_reg_3383;
wire   [15:0] add_ln213_229_fu_2663_p2;
reg   [15:0] add_ln213_229_reg_3389;
wire   [15:0] add_ln213_230_fu_2703_p2;
reg   [15:0] add_ln213_230_reg_3395;
wire   [15:0] add_ln213_231_fu_2743_p2;
reg   [15:0] add_ln213_231_reg_3401;
wire   [15:0] add_ln213_232_fu_2790_p2;
reg   [15:0] add_ln213_232_reg_3407;
wire   [15:0] add_ln213_233_fu_2816_p2;
reg   [15:0] add_ln213_233_reg_3412;
reg   [0:0] tmp_341_reg_3417;
reg    ap_block_pp0_stage0_subdone;
reg    ap_block_pp0_stage0_01001;
wire   [16:0] tmp_fu_465_p4;
wire   [16:0] trunc_ln145_fu_311_p1;
wire   [16:0] add_ln691_fu_653_p2;
wire   [16:0] or_ln_fu_677_p4;
wire   [16:0] tmp_309_fu_475_p4;
wire   [16:0] add_ln691_161_fu_707_p2;
wire   [16:0] or_ln691_s_fu_731_p4;
wire   [16:0] tmp_310_fu_485_p4;
wire   [16:0] add_ln691_162_fu_761_p2;
wire   [16:0] or_ln691_26_fu_785_p4;
wire   [16:0] trunc_ln145_79_fu_495_p4;
wire   [16:0] add_ln691_163_fu_815_p2;
wire   [16:0] or_ln691_28_fu_859_p4;
wire   [16:0] or_ln691_27_fu_839_p4;
wire   [16:0] add_ln691_164_fu_869_p2;
wire   [16:0] or_ln691_30_fu_913_p4;
wire   [16:0] or_ln691_29_fu_893_p4;
wire   [16:0] add_ln691_165_fu_923_p2;
wire   [16:0] or_ln691_32_fu_967_p4;
wire   [16:0] or_ln691_31_fu_947_p4;
wire   [16:0] add_ln691_166_fu_977_p2;
wire   [16:0] or_ln691_34_fu_1021_p4;
wire   [16:0] or_ln691_33_fu_1001_p4;
wire   [16:0] add_ln691_167_fu_1031_p2;
wire   [16:0] or_ln691_36_fu_1075_p4;
wire   [16:0] or_ln691_35_fu_1055_p4;
wire   [16:0] add_ln691_168_fu_1085_p2;
wire   [16:0] or_ln691_38_fu_1129_p4;
wire   [16:0] or_ln691_37_fu_1109_p4;
wire   [16:0] add_ln691_169_fu_1139_p2;
wire   [16:0] or_ln691_40_fu_1183_p4;
wire   [16:0] or_ln691_39_fu_1163_p4;
wire   [16:0] add_ln691_170_fu_1193_p2;
wire   [16:0] or_ln691_42_fu_1237_p4;
wire   [16:0] or_ln691_41_fu_1217_p4;
wire   [16:0] add_ln691_171_fu_1247_p2;
wire   [16:0] or_ln691_44_fu_1291_p4;
wire   [16:0] or_ln691_43_fu_1271_p4;
wire   [16:0] add_ln691_172_fu_1301_p2;
wire   [16:0] or_ln691_46_fu_1345_p4;
wire   [16:0] or_ln691_45_fu_1325_p4;
wire   [16:0] add_ln691_173_fu_1355_p2;
wire   [16:0] or_ln691_48_fu_1399_p4;
wire   [16:0] or_ln691_47_fu_1379_p4;
wire   [16:0] add_ln691_174_fu_1409_p2;
wire   [16:0] or_ln691_50_fu_1453_p4;
wire   [16:0] or_ln691_49_fu_1433_p4;
wire   [16:0] add_ln691_175_fu_1463_p2;
wire   [15:0] zext_ln1497_fu_1477_p1;
wire   [15:0] add_ln213_fu_1483_p2;
wire   [7:0] zext_ln213_fu_1480_p1;
wire   [7:0] add_ln497_16_fu_1493_p2;
wire   [15:0] add_ln213_185_fu_1488_p2;
wire   [15:0] zext_ln1497_158_fu_1513_p1;
wire   [15:0] add_ln213_196_fu_1519_p2;
wire   [7:0] zext_ln213_20_fu_1516_p1;
wire   [7:0] add_ln497_17_fu_1529_p2;
wire   [15:0] add_ln213_187_fu_1524_p2;
wire   [15:0] zext_ln1497_159_fu_1549_p1;
wire   [15:0] add_ln213_198_fu_1555_p2;
wire   [7:0] zext_ln213_21_fu_1552_p1;
wire   [7:0] add_ln497_18_fu_1565_p2;
wire   [15:0] add_ln213_189_fu_1560_p2;
wire   [15:0] zext_ln1497_160_fu_1585_p1;
wire   [15:0] add_ln213_200_fu_1591_p2;
wire   [7:0] zext_ln213_22_fu_1588_p1;
wire   [7:0] add_ln497_19_fu_1601_p2;
wire   [15:0] add_ln213_191_fu_1596_p2;
wire   [15:0] zext_ln1497_161_fu_1621_p1;
wire   [15:0] add_ln213_202_fu_1627_p2;
wire   [7:0] zext_ln213_23_fu_1624_p1;
wire   [7:0] add_ln497_20_fu_1637_p2;
wire   [15:0] add_ln213_193_fu_1632_p2;
wire   [15:0] zext_ln1497_162_fu_1657_p1;
wire   [15:0] add_ln213_204_fu_1663_p2;
wire   [7:0] zext_ln213_24_fu_1660_p1;
wire   [7:0] add_ln497_21_fu_1673_p2;
wire   [15:0] add_ln213_195_fu_1668_p2;
wire   [15:0] zext_ln1497_163_fu_1693_p1;
wire   [15:0] add_ln213_206_fu_1699_p2;
wire   [7:0] zext_ln213_25_fu_1696_p1;
wire   [7:0] add_ln497_22_fu_1709_p2;
wire   [15:0] add_ln213_197_fu_1704_p2;
wire   [15:0] zext_ln1497_164_fu_1729_p1;
wire   [15:0] add_ln213_208_fu_1735_p2;
wire   [7:0] zext_ln213_26_fu_1732_p1;
wire   [7:0] add_ln497_23_fu_1745_p2;
wire   [15:0] add_ln213_199_fu_1740_p2;
wire   [15:0] zext_ln1497_165_fu_1765_p1;
wire   [15:0] add_ln213_210_fu_1771_p2;
wire   [7:0] zext_ln213_27_fu_1768_p1;
wire   [7:0] add_ln497_24_fu_1781_p2;
wire   [15:0] add_ln213_201_fu_1776_p2;
wire   [15:0] zext_ln1497_166_fu_1801_p1;
wire   [15:0] add_ln213_212_fu_1807_p2;
wire   [7:0] zext_ln213_28_fu_1804_p1;
wire   [7:0] add_ln497_25_fu_1817_p2;
wire   [15:0] add_ln213_203_fu_1812_p2;
wire   [15:0] zext_ln1497_167_fu_1837_p1;
wire   [15:0] add_ln213_214_fu_1843_p2;
wire   [7:0] zext_ln213_29_fu_1840_p1;
wire   [7:0] add_ln497_26_fu_1853_p2;
wire   [15:0] add_ln213_205_fu_1848_p2;
wire   [15:0] zext_ln1497_168_fu_1873_p1;
wire   [15:0] add_ln213_216_fu_1879_p2;
wire   [7:0] zext_ln213_30_fu_1876_p1;
wire   [7:0] add_ln497_27_fu_1889_p2;
wire   [15:0] add_ln213_207_fu_1884_p2;
wire   [15:0] zext_ln1497_169_fu_1909_p1;
wire   [15:0] add_ln213_218_fu_1915_p2;
wire   [7:0] zext_ln213_31_fu_1912_p1;
wire   [7:0] add_ln497_28_fu_1925_p2;
wire   [15:0] add_ln213_209_fu_1920_p2;
wire   [15:0] zext_ln1497_170_fu_1945_p1;
wire   [15:0] add_ln213_220_fu_1951_p2;
wire   [7:0] zext_ln213_32_fu_1948_p1;
wire   [7:0] add_ln497_29_fu_1961_p2;
wire   [15:0] add_ln213_211_fu_1956_p2;
wire   [15:0] zext_ln1497_171_fu_1981_p1;
wire   [15:0] add_ln213_222_fu_1987_p2;
wire   [7:0] zext_ln213_33_fu_1984_p1;
wire   [7:0] add_ln497_30_fu_1997_p2;
wire   [15:0] add_ln213_213_fu_1992_p2;
wire   [15:0] zext_ln1497_172_fu_2017_p1;
wire   [15:0] add_ln213_235_fu_2023_p2;
wire   [7:0] zext_ln213_34_fu_2020_p1;
wire   [7:0] add_ln497_31_fu_2033_p2;
wire   [15:0] add_ln213_215_fu_2028_p2;
wire   [7:0] trunc_ln497_8_fu_1791_p4;
wire   [15:0] tmp_147_i_fu_2053_p3;
wire   [7:0] trunc_ln_fu_1503_p4;
wire   [15:0] tmp_148_i_fu_2065_p3;
wire   [16:0] zext_ln691_fu_2061_p1;
wire   [16:0] zext_ln691_155_fu_2073_p1;
wire   [16:0] add_ln691_176_fu_2077_p2;
wire   [15:0] zext_ln1497_173_fu_2091_p1;
wire   [15:0] add_ln213_236_fu_2095_p2;
wire   [15:0] add_ln213_217_fu_2101_p2;
wire   [7:0] trunc_ln497_9_fu_1827_p4;
wire   [15:0] tmp_149_i_fu_2117_p3;
wire   [7:0] trunc_ln497_1_fu_1539_p4;
wire   [15:0] tmp_150_i_fu_2129_p3;
wire   [16:0] zext_ln691_157_fu_2137_p1;
wire   [16:0] zext_ln691_156_fu_2125_p1;
wire   [16:0] add_ln691_177_fu_2141_p2;
wire   [15:0] zext_ln1497_174_fu_2155_p1;
wire   [15:0] add_ln213_237_fu_2159_p2;
wire   [15:0] add_ln213_219_fu_2165_p2;
wire   [7:0] trunc_ln497_s_fu_1863_p4;
wire   [15:0] tmp_151_i_fu_2181_p3;
wire   [7:0] trunc_ln497_2_fu_1575_p4;
wire   [15:0] tmp_152_i_fu_2193_p3;
wire   [16:0] zext_ln691_159_fu_2201_p1;
wire   [16:0] zext_ln691_158_fu_2189_p1;
wire   [16:0] add_ln691_178_fu_2205_p2;
wire   [15:0] zext_ln1497_175_fu_2219_p1;
wire   [15:0] add_ln213_238_fu_2223_p2;
wire   [15:0] add_ln213_221_fu_2229_p2;
wire   [7:0] trunc_ln497_10_fu_1899_p4;
wire   [15:0] tmp_153_i_fu_2245_p3;
wire   [7:0] trunc_ln497_3_fu_1611_p4;
wire   [15:0] tmp_154_i_fu_2257_p3;
wire   [16:0] zext_ln691_161_fu_2265_p1;
wire   [16:0] zext_ln691_160_fu_2253_p1;
wire   [16:0] add_ln691_179_fu_2269_p2;
wire   [15:0] zext_ln1497_176_fu_2283_p1;
wire   [15:0] add_ln213_239_fu_2287_p2;
wire   [15:0] add_ln213_223_fu_2293_p2;
wire   [7:0] trunc_ln497_11_fu_1935_p4;
wire   [7:0] add_ln497_12_fu_1930_p2;
wire   [15:0] tmp_155_i_fu_2309_p3;
wire   [7:0] trunc_ln497_4_fu_1647_p4;
wire   [7:0] add_ln497_4_fu_1642_p2;
wire   [15:0] tmp_156_i_fu_2321_p3;
wire   [16:0] zext_ln691_163_fu_2329_p1;
wire   [16:0] zext_ln691_162_fu_2317_p1;
wire   [16:0] add_ln691_180_fu_2333_p2;
wire   [0:0] tmp_331_fu_2339_p3;
wire   [15:0] zext_ln1497_177_fu_2347_p1;
wire   [15:0] add_ln213_240_fu_2351_p2;
wire   [7:0] trunc_ln497_12_fu_1971_p4;
wire   [7:0] add_ln497_13_fu_1966_p2;
wire   [15:0] tmp_157_i_fu_2363_p3;
wire   [7:0] trunc_ln497_5_fu_1683_p4;
wire   [7:0] add_ln497_5_fu_1678_p2;
wire   [15:0] tmp_158_i_fu_2375_p3;
wire   [16:0] zext_ln691_166_fu_2383_p1;
wire   [16:0] zext_ln691_165_fu_2371_p1;
wire   [16:0] add_ln691_181_fu_2387_p2;
wire   [0:0] tmp_332_fu_2393_p3;
wire   [15:0] zext_ln1497_178_fu_2401_p1;
wire   [15:0] add_ln213_241_fu_2405_p2;
wire   [7:0] trunc_ln497_13_fu_2007_p4;
wire   [7:0] add_ln497_14_fu_2002_p2;
wire   [15:0] tmp_159_i_fu_2417_p3;
wire   [7:0] trunc_ln497_6_fu_1719_p4;
wire   [7:0] add_ln497_6_fu_1714_p2;
wire   [15:0] tmp_160_i_fu_2429_p3;
wire   [16:0] zext_ln691_169_fu_2437_p1;
wire   [16:0] zext_ln691_168_fu_2425_p1;
wire   [16:0] add_ln691_182_fu_2441_p2;
wire   [0:0] tmp_333_fu_2447_p3;
wire   [15:0] zext_ln1497_179_fu_2455_p1;
wire   [15:0] add_ln213_242_fu_2459_p2;
wire   [7:0] trunc_ln497_14_fu_2043_p4;
wire   [7:0] add_ln497_15_fu_2038_p2;
wire   [15:0] tmp_161_i_fu_2471_p3;
wire   [7:0] trunc_ln497_7_fu_1755_p4;
wire   [7:0] add_ln497_7_fu_1750_p2;
wire   [15:0] tmp_162_i_fu_2483_p3;
wire   [16:0] zext_ln691_172_fu_2491_p1;
wire   [16:0] zext_ln691_171_fu_2479_p1;
wire   [16:0] add_ln691_183_fu_2495_p2;
wire   [0:0] tmp_334_fu_2501_p3;
wire   [15:0] zext_ln1497_180_fu_2509_p1;
wire   [15:0] add_ln213_243_fu_2513_p2;
wire   [7:0] zext_ln213_35_fu_2525_p1;
wire   [7:0] add_ln507_4_fu_2528_p2;
wire   [7:0] zext_ln213_36_fu_2538_p1;
wire   [7:0] add_ln507_5_fu_2541_p2;
wire   [7:0] zext_ln213_37_fu_2551_p1;
wire   [7:0] add_ln507_6_fu_2554_p2;
wire   [7:0] zext_ln213_38_fu_2564_p1;
wire   [7:0] add_ln507_7_fu_2567_p2;
wire   [7:0] add_ln507_fu_2533_p2;
wire   [15:0] tmp_163_i_fu_2589_p3;
wire   [16:0] zext_ln691_174_fu_2596_p1;
wire   [16:0] zext_ln691_164_fu_2577_p1;
wire   [16:0] add_ln691_184_fu_2600_p2;
wire   [0:0] tmp_335_fu_2606_p3;
wire   [15:0] zext_ln1497_181_fu_2614_p1;
wire   [15:0] add_ln213_244_fu_2618_p2;
wire   [7:0] add_ln507_1_fu_2546_p2;
wire   [15:0] tmp_164_i_fu_2629_p3;
wire   [16:0] zext_ln691_176_fu_2636_p1;
wire   [16:0] zext_ln691_167_fu_2580_p1;
wire   [16:0] add_ln691_185_fu_2640_p2;
wire   [0:0] tmp_336_fu_2646_p3;
wire   [15:0] zext_ln1497_182_fu_2654_p1;
wire   [15:0] add_ln213_245_fu_2658_p2;
wire   [7:0] add_ln507_2_fu_2559_p2;
wire   [15:0] tmp_165_i_fu_2669_p3;
wire   [16:0] zext_ln691_178_fu_2676_p1;
wire   [16:0] zext_ln691_170_fu_2583_p1;
wire   [16:0] add_ln691_186_fu_2680_p2;
wire   [0:0] tmp_337_fu_2686_p3;
wire   [15:0] zext_ln1497_183_fu_2694_p1;
wire   [15:0] add_ln213_246_fu_2698_p2;
wire   [7:0] add_ln507_3_fu_2572_p2;
wire   [15:0] tmp_166_i_fu_2709_p3;
wire   [16:0] zext_ln691_180_fu_2716_p1;
wire   [16:0] zext_ln691_173_fu_2586_p1;
wire   [16:0] add_ln691_187_fu_2720_p2;
wire   [0:0] tmp_338_fu_2726_p3;
wire   [15:0] zext_ln1497_184_fu_2734_p1;
wire   [15:0] add_ln213_247_fu_2738_p2;
wire   [16:0] zext_ln691_179_fu_2755_p1;
wire   [16:0] zext_ln691_175_fu_2749_p1;
wire   [16:0] zext_ln691_181_fu_2758_p1;
wire   [16:0] zext_ln691_177_fu_2752_p1;
wire   [16:0] add_ln691_188_fu_2761_p2;
wire   [0:0] tmp_339_fu_2773_p3;
wire   [15:0] zext_ln1497_185_fu_2781_p1;
wire   [15:0] add_ln213_248_fu_2785_p2;
wire   [16:0] add_ln691_189_fu_2767_p2;
wire   [0:0] tmp_340_fu_2799_p3;
wire   [15:0] zext_ln1497_187_fu_2807_p1;
wire   [15:0] add_ln213_249_fu_2811_p2;
wire   [16:0] zext_ln691_182_fu_2821_p1;
wire   [16:0] zext_ln1497_186_fu_2795_p1;
wire   [16:0] add_ln691_190_fu_2825_p2;
wire   [15:0] zext_ln1497_188_fu_2839_p1;
wire   [15:0] add_ln213_250_fu_2842_p2;
wire   [15:0] add_ln213_234_fu_2847_p2;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to3;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_i_reg_2859 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln213_224_reg_3359 <= add_ln213_224_fu_2357_p2;
        add_ln213_225_reg_3365 <= add_ln213_225_fu_2411_p2;
        add_ln213_226_reg_3371 <= add_ln213_226_fu_2465_p2;
        add_ln213_227_reg_3377 <= add_ln213_227_fu_2519_p2;
        add_ln497_10_reg_3309 <= add_ln497_10_fu_1858_p2;
        add_ln497_11_reg_3314 <= add_ln497_11_fu_1894_p2;
        add_ln497_1_reg_3284 <= add_ln497_1_fu_1534_p2;
        add_ln497_2_reg_3289 <= add_ln497_2_fu_1570_p2;
        add_ln497_3_reg_3294 <= add_ln497_3_fu_1606_p2;
        add_ln497_8_reg_3299 <= add_ln497_8_fu_1786_p2;
        add_ln497_9_reg_3304 <= add_ln497_9_fu_1822_p2;
        add_ln497_reg_3279 <= add_ln497_fu_1498_p2;
        tmp_327_reg_3319 <= add_ln691_176_fu_2077_p2[32'd16];
        tmp_328_reg_3329 <= add_ln691_177_fu_2141_p2[32'd16];
        tmp_329_reg_3339 <= add_ln691_178_fu_2205_p2[32'd16];
        tmp_330_reg_3349 <= add_ln691_179_fu_2269_p2[32'd16];
        trunc_ln1_reg_3324 <= {{add_ln213_217_fu_2101_p2[15:8]}};
        trunc_ln507_1_reg_3334 <= {{add_ln213_219_fu_2165_p2[15:8]}};
        trunc_ln507_2_reg_3344 <= {{add_ln213_221_fu_2229_p2[15:8]}};
        trunc_ln507_3_reg_3354 <= {{add_ln213_223_fu_2293_p2[15:8]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_i_reg_2859_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln213_228_reg_3383 <= add_ln213_228_fu_2623_p2;
        add_ln213_229_reg_3389 <= add_ln213_229_fu_2663_p2;
        add_ln213_230_reg_3395 <= add_ln213_230_fu_2703_p2;
        add_ln213_231_reg_3401 <= add_ln213_231_fu_2743_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_i_reg_2859_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln213_232_reg_3407 <= add_ln213_232_fu_2790_p2;
        add_ln213_233_reg_3412 <= add_ln213_233_fu_2816_p2;
        tmp_341_reg_3417 <= add_ln691_190_fu_2825_p2[32'd16];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_i_nbreadreq_fu_290_p3 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        or_ln2_reg_3045 <= {{txEng_subChecksumsFifo_dout[79:64]}};
        or_ln691_52_reg_3024 <= {{txEng_subChecksumsFifo_dout[47:32]}};
        or_ln691_53_reg_3066 <= {{txEng_subChecksumsFifo_dout[111:96]}};
        or_ln691_54_reg_3087 <= {{txEng_subChecksumsFifo_dout[655:640]}};
        or_ln691_55_reg_3092 <= {{txEng_subChecksumsFifo_dout[143:128]}};
        or_ln691_56_reg_3103 <= {{txEng_subChecksumsFifo_dout[687:672]}};
        or_ln691_57_reg_3108 <= {{txEng_subChecksumsFifo_dout[175:160]}};
        or_ln691_58_reg_3119 <= {{txEng_subChecksumsFifo_dout[719:704]}};
        or_ln691_59_reg_3124 <= {{txEng_subChecksumsFifo_dout[207:192]}};
        or_ln691_60_reg_3135 <= {{txEng_subChecksumsFifo_dout[751:736]}};
        or_ln691_61_reg_3140 <= {{txEng_subChecksumsFifo_dout[239:224]}};
        or_ln691_62_reg_3151 <= {{txEng_subChecksumsFifo_dout[783:768]}};
        or_ln691_63_reg_3156 <= {{txEng_subChecksumsFifo_dout[271:256]}};
        or_ln691_64_reg_3167 <= {{txEng_subChecksumsFifo_dout[815:800]}};
        or_ln691_65_reg_3172 <= {{txEng_subChecksumsFifo_dout[303:288]}};
        or_ln691_66_reg_3183 <= {{txEng_subChecksumsFifo_dout[847:832]}};
        or_ln691_67_reg_3188 <= {{txEng_subChecksumsFifo_dout[335:320]}};
        or_ln691_68_reg_3199 <= {{txEng_subChecksumsFifo_dout[879:864]}};
        or_ln691_69_reg_3204 <= {{txEng_subChecksumsFifo_dout[367:352]}};
        or_ln691_70_reg_3215 <= {{txEng_subChecksumsFifo_dout[911:896]}};
        or_ln691_71_reg_3220 <= {{txEng_subChecksumsFifo_dout[399:384]}};
        or_ln691_72_reg_3231 <= {{txEng_subChecksumsFifo_dout[943:928]}};
        or_ln691_73_reg_3236 <= {{txEng_subChecksumsFifo_dout[431:416]}};
        or_ln691_74_reg_3247 <= {{txEng_subChecksumsFifo_dout[975:960]}};
        or_ln691_75_reg_3252 <= {{txEng_subChecksumsFifo_dout[463:448]}};
        or_ln691_76_reg_3263 <= {{txEng_subChecksumsFifo_dout[1007:992]}};
        or_ln691_77_reg_3268 <= {{txEng_subChecksumsFifo_dout[495:480]}};
        tmp_311_reg_3018 <= add_ln691_fu_653_p2[32'd16];
        tmp_312_reg_3039 <= add_ln691_161_fu_707_p2[32'd16];
        tmp_313_reg_3060 <= add_ln691_162_fu_761_p2[32'd16];
        tmp_314_reg_3081 <= add_ln691_163_fu_815_p2[32'd16];
        tmp_315_reg_3097 <= add_ln691_164_fu_869_p2[32'd16];
        tmp_316_reg_3113 <= add_ln691_165_fu_923_p2[32'd16];
        tmp_317_reg_3129 <= add_ln691_166_fu_977_p2[32'd16];
        tmp_318_reg_3145 <= add_ln691_167_fu_1031_p2[32'd16];
        tmp_319_reg_3161 <= add_ln691_168_fu_1085_p2[32'd16];
        tmp_320_reg_3177 <= add_ln691_169_fu_1139_p2[32'd16];
        tmp_321_reg_3193 <= add_ln691_170_fu_1193_p2[32'd16];
        tmp_322_reg_3209 <= add_ln691_171_fu_1247_p2[32'd16];
        tmp_323_reg_3225 <= add_ln691_172_fu_1301_p2[32'd16];
        tmp_324_reg_3241 <= add_ln691_173_fu_1355_p2[32'd16];
        tmp_325_reg_3257 <= add_ln691_174_fu_1409_p2[32'd16];
        tmp_326_reg_3273 <= add_ln691_175_fu_1463_p2[32'd16];
        trunc_ln145_65_reg_2868 <= {{txEng_subChecksumsFifo_dout[71:64]}};
        trunc_ln145_66_reg_2873 <= {{txEng_subChecksumsFifo_dout[103:96]}};
        trunc_ln145_67_reg_2878 <= {{txEng_subChecksumsFifo_dout[135:128]}};
        trunc_ln145_68_reg_2883 <= {{txEng_subChecksumsFifo_dout[167:160]}};
        trunc_ln145_69_reg_2888 <= {{txEng_subChecksumsFifo_dout[199:192]}};
        trunc_ln145_70_reg_2893 <= {{txEng_subChecksumsFifo_dout[231:224]}};
        trunc_ln145_71_reg_2898 <= {{txEng_subChecksumsFifo_dout[263:256]}};
        trunc_ln145_72_reg_2903 <= {{txEng_subChecksumsFifo_dout[295:288]}};
        trunc_ln145_73_reg_2908 <= {{txEng_subChecksumsFifo_dout[327:320]}};
        trunc_ln145_74_reg_2913 <= {{txEng_subChecksumsFifo_dout[359:352]}};
        trunc_ln145_75_reg_2918 <= {{txEng_subChecksumsFifo_dout[391:384]}};
        trunc_ln145_76_reg_2923 <= {{txEng_subChecksumsFifo_dout[423:416]}};
        trunc_ln145_77_reg_2928 <= {{txEng_subChecksumsFifo_dout[455:448]}};
        trunc_ln145_78_reg_2933 <= {{txEng_subChecksumsFifo_dout[487:480]}};
        trunc_ln145_80_reg_2938 <= {{txEng_subChecksumsFifo_dout[647:640]}};
        trunc_ln145_81_reg_2943 <= {{txEng_subChecksumsFifo_dout[679:672]}};
        trunc_ln145_82_reg_2948 <= {{txEng_subChecksumsFifo_dout[711:704]}};
        trunc_ln145_83_reg_2953 <= {{txEng_subChecksumsFifo_dout[743:736]}};
        trunc_ln145_84_reg_2958 <= {{txEng_subChecksumsFifo_dout[775:768]}};
        trunc_ln145_85_reg_2963 <= {{txEng_subChecksumsFifo_dout[807:800]}};
        trunc_ln145_86_reg_2968 <= {{txEng_subChecksumsFifo_dout[839:832]}};
        trunc_ln145_87_reg_2973 <= {{txEng_subChecksumsFifo_dout[871:864]}};
        trunc_ln145_88_reg_2978 <= {{txEng_subChecksumsFifo_dout[903:896]}};
        trunc_ln145_89_reg_2983 <= {{txEng_subChecksumsFifo_dout[935:928]}};
        trunc_ln145_90_reg_2988 <= {{txEng_subChecksumsFifo_dout[967:960]}};
        trunc_ln145_91_reg_2993 <= {{txEng_subChecksumsFifo_dout[999:992]}};
        trunc_ln145_s_reg_2863 <= {{txEng_subChecksumsFifo_dout[39:32]}};
        trunc_ln691_10_reg_3050 <= {{txEng_subChecksumsFifo_dout[583:576]}};
        trunc_ln691_11_reg_3055 <= {{txEng_subChecksumsFifo_dout[591:576]}};
        trunc_ln691_12_reg_3071 <= {{txEng_subChecksumsFifo_dout[615:608]}};
        trunc_ln691_13_reg_3076 <= {{txEng_subChecksumsFifo_dout[623:608]}};
        trunc_ln691_69_reg_3008 <= trunc_ln691_69_fu_639_p1;
        trunc_ln691_7_reg_3013 <= {{txEng_subChecksumsFifo_dout[527:512]}};
        trunc_ln691_8_reg_3029 <= {{txEng_subChecksumsFifo_dout[551:544]}};
        trunc_ln691_9_reg_3034 <= {{txEng_subChecksumsFifo_dout[559:544]}};
        trunc_ln691_reg_2998 <= trunc_ln691_fu_625_p1;
        trunc_ln691_s_reg_3003 <= {{txEng_subChecksumsFifo_dout[519:512]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_i_reg_2859 <= tmp_i_nbreadreq_fu_290_p3;
        tmp_i_reg_2859_pp0_iter1_reg <= tmp_i_reg_2859;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        tmp_i_reg_2859_pp0_iter2_reg <= tmp_i_reg_2859_pp0_iter1_reg;
        tmp_i_reg_2859_pp0_iter3_reg <= tmp_i_reg_2859_pp0_iter2_reg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to3 = 1'b1;
    end else begin
        ap_idle_pp0_0to3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to3 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (tmp_i_nbreadreq_fu_290_p3 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_done_reg == 1'b0))) begin
        txEng_subChecksumsFifo_blk_n = txEng_subChecksumsFifo_empty_n;
    end else begin
        txEng_subChecksumsFifo_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_i_nbreadreq_fu_290_p3 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        txEng_subChecksumsFifo_read = 1'b1;
    end else begin
        txEng_subChecksumsFifo_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (tmp_i_reg_2859_pp0_iter3_reg == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        txEng_tcpChecksumFifo_blk_n = txEng_tcpChecksumFifo_full_n;
    end else begin
        txEng_tcpChecksumFifo_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_i_reg_2859_pp0_iter3_reg == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        txEng_tcpChecksumFifo_write = 1'b1;
    end else begin
        txEng_tcpChecksumFifo_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln213_185_fu_1488_p2 = (add_ln213_fu_1483_p2 + trunc_ln691_7_reg_3013);

assign add_ln213_187_fu_1524_p2 = (add_ln213_196_fu_1519_p2 + or_ln691_52_reg_3024);

assign add_ln213_189_fu_1560_p2 = (add_ln213_198_fu_1555_p2 + or_ln2_reg_3045);

assign add_ln213_191_fu_1596_p2 = (add_ln213_200_fu_1591_p2 + or_ln691_53_reg_3066);

assign add_ln213_193_fu_1632_p2 = (add_ln213_202_fu_1627_p2 + or_ln691_55_reg_3092);

assign add_ln213_195_fu_1668_p2 = (add_ln213_204_fu_1663_p2 + or_ln691_57_reg_3108);

assign add_ln213_196_fu_1519_p2 = (trunc_ln691_9_reg_3034 + zext_ln1497_158_fu_1513_p1);

assign add_ln213_197_fu_1704_p2 = (add_ln213_206_fu_1699_p2 + or_ln691_59_reg_3124);

assign add_ln213_198_fu_1555_p2 = (trunc_ln691_11_reg_3055 + zext_ln1497_159_fu_1549_p1);

assign add_ln213_199_fu_1740_p2 = (add_ln213_208_fu_1735_p2 + or_ln691_61_reg_3140);

assign add_ln213_200_fu_1591_p2 = (trunc_ln691_13_reg_3076 + zext_ln1497_160_fu_1585_p1);

assign add_ln213_201_fu_1776_p2 = (add_ln213_210_fu_1771_p2 + or_ln691_63_reg_3156);

assign add_ln213_202_fu_1627_p2 = (or_ln691_54_reg_3087 + zext_ln1497_161_fu_1621_p1);

assign add_ln213_203_fu_1812_p2 = (add_ln213_212_fu_1807_p2 + or_ln691_65_reg_3172);

assign add_ln213_204_fu_1663_p2 = (or_ln691_56_reg_3103 + zext_ln1497_162_fu_1657_p1);

assign add_ln213_205_fu_1848_p2 = (add_ln213_214_fu_1843_p2 + or_ln691_67_reg_3188);

assign add_ln213_206_fu_1699_p2 = (or_ln691_58_reg_3119 + zext_ln1497_163_fu_1693_p1);

assign add_ln213_207_fu_1884_p2 = (add_ln213_216_fu_1879_p2 + or_ln691_69_reg_3204);

assign add_ln213_208_fu_1735_p2 = (or_ln691_60_reg_3135 + zext_ln1497_164_fu_1729_p1);

assign add_ln213_209_fu_1920_p2 = (add_ln213_218_fu_1915_p2 + or_ln691_71_reg_3220);

assign add_ln213_210_fu_1771_p2 = (or_ln691_62_reg_3151 + zext_ln1497_165_fu_1765_p1);

assign add_ln213_211_fu_1956_p2 = (add_ln213_220_fu_1951_p2 + or_ln691_73_reg_3236);

assign add_ln213_212_fu_1807_p2 = (or_ln691_64_reg_3167 + zext_ln1497_166_fu_1801_p1);

assign add_ln213_213_fu_1992_p2 = (add_ln213_222_fu_1987_p2 + or_ln691_75_reg_3252);

assign add_ln213_214_fu_1843_p2 = (or_ln691_66_reg_3183 + zext_ln1497_167_fu_1837_p1);

assign add_ln213_215_fu_2028_p2 = (add_ln213_235_fu_2023_p2 + or_ln691_77_reg_3268);

assign add_ln213_216_fu_1879_p2 = (or_ln691_68_reg_3199 + zext_ln1497_168_fu_1873_p1);

assign add_ln213_217_fu_2101_p2 = (add_ln213_236_fu_2095_p2 + tmp_147_i_fu_2053_p3);

assign add_ln213_218_fu_1915_p2 = (or_ln691_70_reg_3215 + zext_ln1497_169_fu_1909_p1);

assign add_ln213_219_fu_2165_p2 = (add_ln213_237_fu_2159_p2 + tmp_150_i_fu_2129_p3);

assign add_ln213_220_fu_1951_p2 = (or_ln691_72_reg_3231 + zext_ln1497_170_fu_1945_p1);

assign add_ln213_221_fu_2229_p2 = (add_ln213_238_fu_2223_p2 + tmp_152_i_fu_2193_p3);

assign add_ln213_222_fu_1987_p2 = (or_ln691_74_reg_3247 + zext_ln1497_171_fu_1981_p1);

assign add_ln213_223_fu_2293_p2 = (add_ln213_239_fu_2287_p2 + tmp_154_i_fu_2257_p3);

assign add_ln213_224_fu_2357_p2 = (add_ln213_240_fu_2351_p2 + tmp_156_i_fu_2321_p3);

assign add_ln213_225_fu_2411_p2 = (add_ln213_241_fu_2405_p2 + tmp_158_i_fu_2375_p3);

assign add_ln213_226_fu_2465_p2 = (add_ln213_242_fu_2459_p2 + tmp_160_i_fu_2429_p3);

assign add_ln213_227_fu_2519_p2 = (add_ln213_243_fu_2513_p2 + tmp_162_i_fu_2483_p3);

assign add_ln213_228_fu_2623_p2 = (add_ln213_244_fu_2618_p2 + tmp_163_i_fu_2589_p3);

assign add_ln213_229_fu_2663_p2 = (add_ln213_245_fu_2658_p2 + tmp_164_i_fu_2629_p3);

assign add_ln213_230_fu_2703_p2 = (add_ln213_246_fu_2698_p2 + tmp_165_i_fu_2669_p3);

assign add_ln213_231_fu_2743_p2 = (add_ln213_247_fu_2738_p2 + tmp_166_i_fu_2709_p3);

assign add_ln213_232_fu_2790_p2 = (add_ln213_248_fu_2785_p2 + add_ln213_230_reg_3395);

assign add_ln213_233_fu_2816_p2 = (add_ln213_249_fu_2811_p2 + add_ln213_231_reg_3401);

assign add_ln213_234_fu_2847_p2 = (add_ln213_250_fu_2842_p2 + add_ln213_233_reg_3412);

assign add_ln213_235_fu_2023_p2 = (or_ln691_76_reg_3263 + zext_ln1497_172_fu_2017_p1);

assign add_ln213_236_fu_2095_p2 = (tmp_148_i_fu_2065_p3 + zext_ln1497_173_fu_2091_p1);

assign add_ln213_237_fu_2159_p2 = (tmp_149_i_fu_2117_p3 + zext_ln1497_174_fu_2155_p1);

assign add_ln213_238_fu_2223_p2 = (tmp_151_i_fu_2181_p3 + zext_ln1497_175_fu_2219_p1);

assign add_ln213_239_fu_2287_p2 = (tmp_153_i_fu_2245_p3 + zext_ln1497_176_fu_2283_p1);

assign add_ln213_240_fu_2351_p2 = (tmp_155_i_fu_2309_p3 + zext_ln1497_177_fu_2347_p1);

assign add_ln213_241_fu_2405_p2 = (tmp_157_i_fu_2363_p3 + zext_ln1497_178_fu_2401_p1);

assign add_ln213_242_fu_2459_p2 = (tmp_159_i_fu_2417_p3 + zext_ln1497_179_fu_2455_p1);

assign add_ln213_243_fu_2513_p2 = (tmp_161_i_fu_2471_p3 + zext_ln1497_180_fu_2509_p1);

assign add_ln213_244_fu_2618_p2 = (add_ln213_224_reg_3359 + zext_ln1497_181_fu_2614_p1);

assign add_ln213_245_fu_2658_p2 = (add_ln213_225_reg_3365 + zext_ln1497_182_fu_2654_p1);

assign add_ln213_246_fu_2698_p2 = (add_ln213_226_reg_3371 + zext_ln1497_183_fu_2694_p1);

assign add_ln213_247_fu_2738_p2 = (add_ln213_227_reg_3377 + zext_ln1497_184_fu_2734_p1);

assign add_ln213_248_fu_2785_p2 = (add_ln213_228_reg_3383 + zext_ln1497_185_fu_2781_p1);

assign add_ln213_249_fu_2811_p2 = (add_ln213_229_reg_3389 + zext_ln1497_187_fu_2807_p1);

assign add_ln213_250_fu_2842_p2 = (add_ln213_232_reg_3407 + zext_ln1497_188_fu_2839_p1);

assign add_ln213_fu_1483_p2 = (trunc_ln691_69_reg_3008 + zext_ln1497_fu_1477_p1);

assign add_ln497_10_fu_1858_p2 = (add_ln497_26_fu_1853_p2 + trunc_ln145_73_reg_2908);

assign add_ln497_11_fu_1894_p2 = (add_ln497_27_fu_1889_p2 + trunc_ln145_74_reg_2913);

assign add_ln497_12_fu_1930_p2 = (add_ln497_28_fu_1925_p2 + trunc_ln145_75_reg_2918);

assign add_ln497_13_fu_1966_p2 = (add_ln497_29_fu_1961_p2 + trunc_ln145_76_reg_2923);

assign add_ln497_14_fu_2002_p2 = (add_ln497_30_fu_1997_p2 + trunc_ln145_77_reg_2928);

assign add_ln497_15_fu_2038_p2 = (add_ln497_31_fu_2033_p2 + trunc_ln145_78_reg_2933);

assign add_ln497_16_fu_1493_p2 = (trunc_ln691_reg_2998 + zext_ln213_fu_1480_p1);

assign add_ln497_17_fu_1529_p2 = (trunc_ln691_8_reg_3029 + zext_ln213_20_fu_1516_p1);

assign add_ln497_18_fu_1565_p2 = (trunc_ln691_10_reg_3050 + zext_ln213_21_fu_1552_p1);

assign add_ln497_19_fu_1601_p2 = (trunc_ln691_12_reg_3071 + zext_ln213_22_fu_1588_p1);

assign add_ln497_1_fu_1534_p2 = (add_ln497_17_fu_1529_p2 + trunc_ln145_s_reg_2863);

assign add_ln497_20_fu_1637_p2 = (trunc_ln145_80_reg_2938 + zext_ln213_23_fu_1624_p1);

assign add_ln497_21_fu_1673_p2 = (trunc_ln145_81_reg_2943 + zext_ln213_24_fu_1660_p1);

assign add_ln497_22_fu_1709_p2 = (trunc_ln145_82_reg_2948 + zext_ln213_25_fu_1696_p1);

assign add_ln497_23_fu_1745_p2 = (trunc_ln145_83_reg_2953 + zext_ln213_26_fu_1732_p1);

assign add_ln497_24_fu_1781_p2 = (trunc_ln145_84_reg_2958 + zext_ln213_27_fu_1768_p1);

assign add_ln497_25_fu_1817_p2 = (trunc_ln145_85_reg_2963 + zext_ln213_28_fu_1804_p1);

assign add_ln497_26_fu_1853_p2 = (trunc_ln145_86_reg_2968 + zext_ln213_29_fu_1840_p1);

assign add_ln497_27_fu_1889_p2 = (trunc_ln145_87_reg_2973 + zext_ln213_30_fu_1876_p1);

assign add_ln497_28_fu_1925_p2 = (trunc_ln145_88_reg_2978 + zext_ln213_31_fu_1912_p1);

assign add_ln497_29_fu_1961_p2 = (trunc_ln145_89_reg_2983 + zext_ln213_32_fu_1948_p1);

assign add_ln497_2_fu_1570_p2 = (add_ln497_18_fu_1565_p2 + trunc_ln145_65_reg_2868);

assign add_ln497_30_fu_1997_p2 = (trunc_ln145_90_reg_2988 + zext_ln213_33_fu_1984_p1);

assign add_ln497_31_fu_2033_p2 = (trunc_ln145_91_reg_2993 + zext_ln213_34_fu_2020_p1);

assign add_ln497_3_fu_1606_p2 = (add_ln497_19_fu_1601_p2 + trunc_ln145_66_reg_2873);

assign add_ln497_4_fu_1642_p2 = (add_ln497_20_fu_1637_p2 + trunc_ln145_67_reg_2878);

assign add_ln497_5_fu_1678_p2 = (add_ln497_21_fu_1673_p2 + trunc_ln145_68_reg_2883);

assign add_ln497_6_fu_1714_p2 = (add_ln497_22_fu_1709_p2 + trunc_ln145_69_reg_2888);

assign add_ln497_7_fu_1750_p2 = (add_ln497_23_fu_1745_p2 + trunc_ln145_70_reg_2893);

assign add_ln497_8_fu_1786_p2 = (add_ln497_24_fu_1781_p2 + trunc_ln145_71_reg_2898);

assign add_ln497_9_fu_1822_p2 = (add_ln497_25_fu_1817_p2 + trunc_ln145_72_reg_2903);

assign add_ln497_fu_1498_p2 = (add_ln497_16_fu_1493_p2 + trunc_ln691_s_reg_3003);

assign add_ln507_1_fu_2546_p2 = (add_ln507_5_fu_2541_p2 + add_ln497_1_reg_3284);

assign add_ln507_2_fu_2559_p2 = (add_ln507_6_fu_2554_p2 + add_ln497_2_reg_3289);

assign add_ln507_3_fu_2572_p2 = (add_ln507_7_fu_2567_p2 + add_ln497_3_reg_3294);

assign add_ln507_4_fu_2528_p2 = (add_ln497_reg_3279 + zext_ln213_35_fu_2525_p1);

assign add_ln507_5_fu_2541_p2 = (add_ln497_9_reg_3304 + zext_ln213_36_fu_2538_p1);

assign add_ln507_6_fu_2554_p2 = (add_ln497_10_reg_3309 + zext_ln213_37_fu_2551_p1);

assign add_ln507_7_fu_2567_p2 = (add_ln497_11_reg_3314 + zext_ln213_38_fu_2564_p1);

assign add_ln507_fu_2533_p2 = (add_ln507_4_fu_2528_p2 + add_ln497_8_reg_3299);

assign add_ln691_161_fu_707_p2 = (or_ln_fu_677_p4 + tmp_309_fu_475_p4);

assign add_ln691_162_fu_761_p2 = (or_ln691_s_fu_731_p4 + tmp_310_fu_485_p4);

assign add_ln691_163_fu_815_p2 = (or_ln691_26_fu_785_p4 + trunc_ln145_79_fu_495_p4);

assign add_ln691_164_fu_869_p2 = (or_ln691_28_fu_859_p4 + or_ln691_27_fu_839_p4);

assign add_ln691_165_fu_923_p2 = (or_ln691_30_fu_913_p4 + or_ln691_29_fu_893_p4);

assign add_ln691_166_fu_977_p2 = (or_ln691_32_fu_967_p4 + or_ln691_31_fu_947_p4);

assign add_ln691_167_fu_1031_p2 = (or_ln691_34_fu_1021_p4 + or_ln691_33_fu_1001_p4);

assign add_ln691_168_fu_1085_p2 = (or_ln691_36_fu_1075_p4 + or_ln691_35_fu_1055_p4);

assign add_ln691_169_fu_1139_p2 = (or_ln691_38_fu_1129_p4 + or_ln691_37_fu_1109_p4);

assign add_ln691_170_fu_1193_p2 = (or_ln691_40_fu_1183_p4 + or_ln691_39_fu_1163_p4);

assign add_ln691_171_fu_1247_p2 = (or_ln691_42_fu_1237_p4 + or_ln691_41_fu_1217_p4);

assign add_ln691_172_fu_1301_p2 = (or_ln691_44_fu_1291_p4 + or_ln691_43_fu_1271_p4);

assign add_ln691_173_fu_1355_p2 = (or_ln691_46_fu_1345_p4 + or_ln691_45_fu_1325_p4);

assign add_ln691_174_fu_1409_p2 = (or_ln691_48_fu_1399_p4 + or_ln691_47_fu_1379_p4);

assign add_ln691_175_fu_1463_p2 = (or_ln691_50_fu_1453_p4 + or_ln691_49_fu_1433_p4);

assign add_ln691_176_fu_2077_p2 = (zext_ln691_fu_2061_p1 + zext_ln691_155_fu_2073_p1);

assign add_ln691_177_fu_2141_p2 = (zext_ln691_157_fu_2137_p1 + zext_ln691_156_fu_2125_p1);

assign add_ln691_178_fu_2205_p2 = (zext_ln691_159_fu_2201_p1 + zext_ln691_158_fu_2189_p1);

assign add_ln691_179_fu_2269_p2 = (zext_ln691_161_fu_2265_p1 + zext_ln691_160_fu_2253_p1);

assign add_ln691_180_fu_2333_p2 = (zext_ln691_163_fu_2329_p1 + zext_ln691_162_fu_2317_p1);

assign add_ln691_181_fu_2387_p2 = (zext_ln691_166_fu_2383_p1 + zext_ln691_165_fu_2371_p1);

assign add_ln691_182_fu_2441_p2 = (zext_ln691_169_fu_2437_p1 + zext_ln691_168_fu_2425_p1);

assign add_ln691_183_fu_2495_p2 = (zext_ln691_172_fu_2491_p1 + zext_ln691_171_fu_2479_p1);

assign add_ln691_184_fu_2600_p2 = (zext_ln691_174_fu_2596_p1 + zext_ln691_164_fu_2577_p1);

assign add_ln691_185_fu_2640_p2 = (zext_ln691_176_fu_2636_p1 + zext_ln691_167_fu_2580_p1);

assign add_ln691_186_fu_2680_p2 = (zext_ln691_178_fu_2676_p1 + zext_ln691_170_fu_2583_p1);

assign add_ln691_187_fu_2720_p2 = (zext_ln691_180_fu_2716_p1 + zext_ln691_173_fu_2586_p1);

assign add_ln691_188_fu_2761_p2 = (zext_ln691_179_fu_2755_p1 + zext_ln691_175_fu_2749_p1);

assign add_ln691_189_fu_2767_p2 = (zext_ln691_181_fu_2758_p1 + zext_ln691_177_fu_2752_p1);

assign add_ln691_190_fu_2825_p2 = (zext_ln691_182_fu_2821_p1 + zext_ln1497_186_fu_2795_p1);

assign add_ln691_fu_653_p2 = (tmp_fu_465_p4 + trunc_ln145_fu_311_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((tmp_i_reg_2859_pp0_iter3_reg == 1'd1) & (txEng_tcpChecksumFifo_full_n == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((ap_start == 1'b1) & ((ap_done_reg == 1'b1) | ((tmp_i_nbreadreq_fu_290_p3 == 1'd1) & (txEng_subChecksumsFifo_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((tmp_i_reg_2859_pp0_iter3_reg == 1'd1) & (txEng_tcpChecksumFifo_full_n == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((ap_start == 1'b1) & ((ap_done_reg == 1'b1) | ((tmp_i_nbreadreq_fu_290_p3 == 1'd1) & (txEng_subChecksumsFifo_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((tmp_i_reg_2859_pp0_iter3_reg == 1'd1) & (txEng_tcpChecksumFifo_full_n == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((ap_start == 1'b1) & ((ap_done_reg == 1'b1) | ((tmp_i_nbreadreq_fu_290_p3 == 1'd1) & (txEng_subChecksumsFifo_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_done_reg == 1'b1) | ((tmp_i_nbreadreq_fu_290_p3 == 1'd1) & (txEng_subChecksumsFifo_empty_n == 1'b0)));
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state5_pp0_stage0_iter4 = ((tmp_i_reg_2859_pp0_iter3_reg == 1'd1) & (txEng_tcpChecksumFifo_full_n == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign or_ln691_26_fu_785_p4 = {{txEng_subChecksumsFifo_dout[112:96]}};

assign or_ln691_27_fu_839_p4 = {{txEng_subChecksumsFifo_dout[656:640]}};

assign or_ln691_28_fu_859_p4 = {{txEng_subChecksumsFifo_dout[144:128]}};

assign or_ln691_29_fu_893_p4 = {{txEng_subChecksumsFifo_dout[688:672]}};

assign or_ln691_30_fu_913_p4 = {{txEng_subChecksumsFifo_dout[176:160]}};

assign or_ln691_31_fu_947_p4 = {{txEng_subChecksumsFifo_dout[720:704]}};

assign or_ln691_32_fu_967_p4 = {{txEng_subChecksumsFifo_dout[208:192]}};

assign or_ln691_33_fu_1001_p4 = {{txEng_subChecksumsFifo_dout[752:736]}};

assign or_ln691_34_fu_1021_p4 = {{txEng_subChecksumsFifo_dout[240:224]}};

assign or_ln691_35_fu_1055_p4 = {{txEng_subChecksumsFifo_dout[784:768]}};

assign or_ln691_36_fu_1075_p4 = {{txEng_subChecksumsFifo_dout[272:256]}};

assign or_ln691_37_fu_1109_p4 = {{txEng_subChecksumsFifo_dout[816:800]}};

assign or_ln691_38_fu_1129_p4 = {{txEng_subChecksumsFifo_dout[304:288]}};

assign or_ln691_39_fu_1163_p4 = {{txEng_subChecksumsFifo_dout[848:832]}};

assign or_ln691_40_fu_1183_p4 = {{txEng_subChecksumsFifo_dout[336:320]}};

assign or_ln691_41_fu_1217_p4 = {{txEng_subChecksumsFifo_dout[880:864]}};

assign or_ln691_42_fu_1237_p4 = {{txEng_subChecksumsFifo_dout[368:352]}};

assign or_ln691_43_fu_1271_p4 = {{txEng_subChecksumsFifo_dout[912:896]}};

assign or_ln691_44_fu_1291_p4 = {{txEng_subChecksumsFifo_dout[400:384]}};

assign or_ln691_45_fu_1325_p4 = {{txEng_subChecksumsFifo_dout[944:928]}};

assign or_ln691_46_fu_1345_p4 = {{txEng_subChecksumsFifo_dout[432:416]}};

assign or_ln691_47_fu_1379_p4 = {{txEng_subChecksumsFifo_dout[976:960]}};

assign or_ln691_48_fu_1399_p4 = {{txEng_subChecksumsFifo_dout[464:448]}};

assign or_ln691_49_fu_1433_p4 = {{txEng_subChecksumsFifo_dout[1008:992]}};

assign or_ln691_50_fu_1453_p4 = {{txEng_subChecksumsFifo_dout[496:480]}};

assign or_ln691_s_fu_731_p4 = {{txEng_subChecksumsFifo_dout[80:64]}};

assign or_ln_fu_677_p4 = {{txEng_subChecksumsFifo_dout[48:32]}};

assign tmp_147_i_fu_2053_p3 = {{trunc_ln497_8_fu_1791_p4}, {add_ln497_8_fu_1786_p2}};

assign tmp_148_i_fu_2065_p3 = {{trunc_ln_fu_1503_p4}, {add_ln497_fu_1498_p2}};

assign tmp_149_i_fu_2117_p3 = {{trunc_ln497_9_fu_1827_p4}, {add_ln497_9_fu_1822_p2}};

assign tmp_150_i_fu_2129_p3 = {{trunc_ln497_1_fu_1539_p4}, {add_ln497_1_fu_1534_p2}};

assign tmp_151_i_fu_2181_p3 = {{trunc_ln497_s_fu_1863_p4}, {add_ln497_10_fu_1858_p2}};

assign tmp_152_i_fu_2193_p3 = {{trunc_ln497_2_fu_1575_p4}, {add_ln497_2_fu_1570_p2}};

assign tmp_153_i_fu_2245_p3 = {{trunc_ln497_10_fu_1899_p4}, {add_ln497_11_fu_1894_p2}};

assign tmp_154_i_fu_2257_p3 = {{trunc_ln497_3_fu_1611_p4}, {add_ln497_3_fu_1606_p2}};

assign tmp_155_i_fu_2309_p3 = {{trunc_ln497_11_fu_1935_p4}, {add_ln497_12_fu_1930_p2}};

assign tmp_156_i_fu_2321_p3 = {{trunc_ln497_4_fu_1647_p4}, {add_ln497_4_fu_1642_p2}};

assign tmp_157_i_fu_2363_p3 = {{trunc_ln497_12_fu_1971_p4}, {add_ln497_13_fu_1966_p2}};

assign tmp_158_i_fu_2375_p3 = {{trunc_ln497_5_fu_1683_p4}, {add_ln497_5_fu_1678_p2}};

assign tmp_159_i_fu_2417_p3 = {{trunc_ln497_13_fu_2007_p4}, {add_ln497_14_fu_2002_p2}};

assign tmp_160_i_fu_2429_p3 = {{trunc_ln497_6_fu_1719_p4}, {add_ln497_6_fu_1714_p2}};

assign tmp_161_i_fu_2471_p3 = {{trunc_ln497_14_fu_2043_p4}, {add_ln497_15_fu_2038_p2}};

assign tmp_162_i_fu_2483_p3 = {{trunc_ln497_7_fu_1755_p4}, {add_ln497_7_fu_1750_p2}};

assign tmp_163_i_fu_2589_p3 = {{trunc_ln1_reg_3324}, {add_ln507_fu_2533_p2}};

assign tmp_164_i_fu_2629_p3 = {{trunc_ln507_1_reg_3334}, {add_ln507_1_fu_2546_p2}};

assign tmp_165_i_fu_2669_p3 = {{trunc_ln507_2_reg_3344}, {add_ln507_2_fu_2559_p2}};

assign tmp_166_i_fu_2709_p3 = {{trunc_ln507_3_reg_3354}, {add_ln507_3_fu_2572_p2}};

assign tmp_309_fu_475_p4 = {{txEng_subChecksumsFifo_dout[560:544]}};

assign tmp_310_fu_485_p4 = {{txEng_subChecksumsFifo_dout[592:576]}};

assign tmp_327_fu_2083_p3 = add_ln691_176_fu_2077_p2[32'd16];

assign tmp_328_fu_2147_p3 = add_ln691_177_fu_2141_p2[32'd16];

assign tmp_329_fu_2211_p3 = add_ln691_178_fu_2205_p2[32'd16];

assign tmp_330_fu_2275_p3 = add_ln691_179_fu_2269_p2[32'd16];

assign tmp_331_fu_2339_p3 = add_ln691_180_fu_2333_p2[32'd16];

assign tmp_332_fu_2393_p3 = add_ln691_181_fu_2387_p2[32'd16];

assign tmp_333_fu_2447_p3 = add_ln691_182_fu_2441_p2[32'd16];

assign tmp_334_fu_2501_p3 = add_ln691_183_fu_2495_p2[32'd16];

assign tmp_335_fu_2606_p3 = add_ln691_184_fu_2600_p2[32'd16];

assign tmp_336_fu_2646_p3 = add_ln691_185_fu_2640_p2[32'd16];

assign tmp_337_fu_2686_p3 = add_ln691_186_fu_2680_p2[32'd16];

assign tmp_338_fu_2726_p3 = add_ln691_187_fu_2720_p2[32'd16];

assign tmp_339_fu_2773_p3 = add_ln691_188_fu_2761_p2[32'd16];

assign tmp_340_fu_2799_p3 = add_ln691_189_fu_2767_p2[32'd16];

assign tmp_fu_465_p4 = {{txEng_subChecksumsFifo_dout[528:512]}};

assign tmp_i_nbreadreq_fu_290_p3 = txEng_subChecksumsFifo_empty_n;

assign trunc_ln145_79_fu_495_p4 = {{txEng_subChecksumsFifo_dout[624:608]}};

assign trunc_ln145_fu_311_p1 = txEng_subChecksumsFifo_dout[16:0];

assign trunc_ln497_10_fu_1899_p4 = {{add_ln213_207_fu_1884_p2[15:8]}};

assign trunc_ln497_11_fu_1935_p4 = {{add_ln213_209_fu_1920_p2[15:8]}};

assign trunc_ln497_12_fu_1971_p4 = {{add_ln213_211_fu_1956_p2[15:8]}};

assign trunc_ln497_13_fu_2007_p4 = {{add_ln213_213_fu_1992_p2[15:8]}};

assign trunc_ln497_14_fu_2043_p4 = {{add_ln213_215_fu_2028_p2[15:8]}};

assign trunc_ln497_1_fu_1539_p4 = {{add_ln213_187_fu_1524_p2[15:8]}};

assign trunc_ln497_2_fu_1575_p4 = {{add_ln213_189_fu_1560_p2[15:8]}};

assign trunc_ln497_3_fu_1611_p4 = {{add_ln213_191_fu_1596_p2[15:8]}};

assign trunc_ln497_4_fu_1647_p4 = {{add_ln213_193_fu_1632_p2[15:8]}};

assign trunc_ln497_5_fu_1683_p4 = {{add_ln213_195_fu_1668_p2[15:8]}};

assign trunc_ln497_6_fu_1719_p4 = {{add_ln213_197_fu_1704_p2[15:8]}};

assign trunc_ln497_7_fu_1755_p4 = {{add_ln213_199_fu_1740_p2[15:8]}};

assign trunc_ln497_8_fu_1791_p4 = {{add_ln213_201_fu_1776_p2[15:8]}};

assign trunc_ln497_9_fu_1827_p4 = {{add_ln213_203_fu_1812_p2[15:8]}};

assign trunc_ln497_s_fu_1863_p4 = {{add_ln213_205_fu_1848_p2[15:8]}};

assign trunc_ln691_69_fu_639_p1 = txEng_subChecksumsFifo_dout[15:0];

assign trunc_ln691_fu_625_p1 = txEng_subChecksumsFifo_dout[7:0];

assign trunc_ln_fu_1503_p4 = {{add_ln213_185_fu_1488_p2[15:8]}};

assign txEng_tcpChecksumFifo_din = (16'd65535 ^ add_ln213_234_fu_2847_p2);

assign zext_ln1497_158_fu_1513_p1 = tmp_312_reg_3039;

assign zext_ln1497_159_fu_1549_p1 = tmp_313_reg_3060;

assign zext_ln1497_160_fu_1585_p1 = tmp_314_reg_3081;

assign zext_ln1497_161_fu_1621_p1 = tmp_315_reg_3097;

assign zext_ln1497_162_fu_1657_p1 = tmp_316_reg_3113;

assign zext_ln1497_163_fu_1693_p1 = tmp_317_reg_3129;

assign zext_ln1497_164_fu_1729_p1 = tmp_318_reg_3145;

assign zext_ln1497_165_fu_1765_p1 = tmp_319_reg_3161;

assign zext_ln1497_166_fu_1801_p1 = tmp_320_reg_3177;

assign zext_ln1497_167_fu_1837_p1 = tmp_321_reg_3193;

assign zext_ln1497_168_fu_1873_p1 = tmp_322_reg_3209;

assign zext_ln1497_169_fu_1909_p1 = tmp_323_reg_3225;

assign zext_ln1497_170_fu_1945_p1 = tmp_324_reg_3241;

assign zext_ln1497_171_fu_1981_p1 = tmp_325_reg_3257;

assign zext_ln1497_172_fu_2017_p1 = tmp_326_reg_3273;

assign zext_ln1497_173_fu_2091_p1 = tmp_327_fu_2083_p3;

assign zext_ln1497_174_fu_2155_p1 = tmp_328_fu_2147_p3;

assign zext_ln1497_175_fu_2219_p1 = tmp_329_fu_2211_p3;

assign zext_ln1497_176_fu_2283_p1 = tmp_330_fu_2275_p3;

assign zext_ln1497_177_fu_2347_p1 = tmp_331_fu_2339_p3;

assign zext_ln1497_178_fu_2401_p1 = tmp_332_fu_2393_p3;

assign zext_ln1497_179_fu_2455_p1 = tmp_333_fu_2447_p3;

assign zext_ln1497_180_fu_2509_p1 = tmp_334_fu_2501_p3;

assign zext_ln1497_181_fu_2614_p1 = tmp_335_fu_2606_p3;

assign zext_ln1497_182_fu_2654_p1 = tmp_336_fu_2646_p3;

assign zext_ln1497_183_fu_2694_p1 = tmp_337_fu_2686_p3;

assign zext_ln1497_184_fu_2734_p1 = tmp_338_fu_2726_p3;

assign zext_ln1497_185_fu_2781_p1 = tmp_339_fu_2773_p3;

assign zext_ln1497_186_fu_2795_p1 = add_ln213_232_fu_2790_p2;

assign zext_ln1497_187_fu_2807_p1 = tmp_340_fu_2799_p3;

assign zext_ln1497_188_fu_2839_p1 = tmp_341_reg_3417;

assign zext_ln1497_fu_1477_p1 = tmp_311_reg_3018;

assign zext_ln213_20_fu_1516_p1 = tmp_312_reg_3039;

assign zext_ln213_21_fu_1552_p1 = tmp_313_reg_3060;

assign zext_ln213_22_fu_1588_p1 = tmp_314_reg_3081;

assign zext_ln213_23_fu_1624_p1 = tmp_315_reg_3097;

assign zext_ln213_24_fu_1660_p1 = tmp_316_reg_3113;

assign zext_ln213_25_fu_1696_p1 = tmp_317_reg_3129;

assign zext_ln213_26_fu_1732_p1 = tmp_318_reg_3145;

assign zext_ln213_27_fu_1768_p1 = tmp_319_reg_3161;

assign zext_ln213_28_fu_1804_p1 = tmp_320_reg_3177;

assign zext_ln213_29_fu_1840_p1 = tmp_321_reg_3193;

assign zext_ln213_30_fu_1876_p1 = tmp_322_reg_3209;

assign zext_ln213_31_fu_1912_p1 = tmp_323_reg_3225;

assign zext_ln213_32_fu_1948_p1 = tmp_324_reg_3241;

assign zext_ln213_33_fu_1984_p1 = tmp_325_reg_3257;

assign zext_ln213_34_fu_2020_p1 = tmp_326_reg_3273;

assign zext_ln213_35_fu_2525_p1 = tmp_327_reg_3319;

assign zext_ln213_36_fu_2538_p1 = tmp_328_reg_3329;

assign zext_ln213_37_fu_2551_p1 = tmp_329_reg_3339;

assign zext_ln213_38_fu_2564_p1 = tmp_330_reg_3349;

assign zext_ln213_fu_1480_p1 = tmp_311_reg_3018;

assign zext_ln691_155_fu_2073_p1 = tmp_148_i_fu_2065_p3;

assign zext_ln691_156_fu_2125_p1 = tmp_149_i_fu_2117_p3;

assign zext_ln691_157_fu_2137_p1 = tmp_150_i_fu_2129_p3;

assign zext_ln691_158_fu_2189_p1 = tmp_151_i_fu_2181_p3;

assign zext_ln691_159_fu_2201_p1 = tmp_152_i_fu_2193_p3;

assign zext_ln691_160_fu_2253_p1 = tmp_153_i_fu_2245_p3;

assign zext_ln691_161_fu_2265_p1 = tmp_154_i_fu_2257_p3;

assign zext_ln691_162_fu_2317_p1 = tmp_155_i_fu_2309_p3;

assign zext_ln691_163_fu_2329_p1 = tmp_156_i_fu_2321_p3;

assign zext_ln691_164_fu_2577_p1 = add_ln213_224_reg_3359;

assign zext_ln691_165_fu_2371_p1 = tmp_157_i_fu_2363_p3;

assign zext_ln691_166_fu_2383_p1 = tmp_158_i_fu_2375_p3;

assign zext_ln691_167_fu_2580_p1 = add_ln213_225_reg_3365;

assign zext_ln691_168_fu_2425_p1 = tmp_159_i_fu_2417_p3;

assign zext_ln691_169_fu_2437_p1 = tmp_160_i_fu_2429_p3;

assign zext_ln691_170_fu_2583_p1 = add_ln213_226_reg_3371;

assign zext_ln691_171_fu_2479_p1 = tmp_161_i_fu_2471_p3;

assign zext_ln691_172_fu_2491_p1 = tmp_162_i_fu_2483_p3;

assign zext_ln691_173_fu_2586_p1 = add_ln213_227_reg_3377;

assign zext_ln691_174_fu_2596_p1 = tmp_163_i_fu_2589_p3;

assign zext_ln691_175_fu_2749_p1 = add_ln213_228_reg_3383;

assign zext_ln691_176_fu_2636_p1 = tmp_164_i_fu_2629_p3;

assign zext_ln691_177_fu_2752_p1 = add_ln213_229_reg_3389;

assign zext_ln691_178_fu_2676_p1 = tmp_165_i_fu_2669_p3;

assign zext_ln691_179_fu_2755_p1 = add_ln213_230_reg_3395;

assign zext_ln691_180_fu_2716_p1 = tmp_166_i_fu_2709_p3;

assign zext_ln691_181_fu_2758_p1 = add_ln213_231_reg_3401;

assign zext_ln691_182_fu_2821_p1 = add_ln213_233_fu_2816_p2;

assign zext_ln691_fu_2061_p1 = tmp_147_i_fu_2053_p3;

endmodule //toe_top_finalize_ipv4_checksum_32_s
