// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module toe_top_drop_optional_header_fields_512_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        rxEng_dataBuffer3b_dout,
        rxEng_dataBuffer3b_empty_n,
        rxEng_dataBuffer3b_read,
        rxEng_optionalFieldsMetaFifo_dout,
        rxEng_optionalFieldsMetaFifo_empty_n,
        rxEng_optionalFieldsMetaFifo_read,
        rxEng_dataBuffer3_din,
        rxEng_dataBuffer3_full_n,
        rxEng_dataBuffer3_write,
        rxEng_optionalFieldsFifo_din,
        rxEng_optionalFieldsFifo_full_n,
        rxEng_optionalFieldsFifo_write,
        rxEng_dataOffsetFifo_din,
        rxEng_dataOffsetFifo_full_n,
        rxEng_dataOffsetFifo_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [1023:0] rxEng_dataBuffer3b_dout;
input   rxEng_dataBuffer3b_empty_n;
output   rxEng_dataBuffer3b_read;
input  [15:0] rxEng_optionalFieldsMetaFifo_dout;
input   rxEng_optionalFieldsMetaFifo_empty_n;
output   rxEng_optionalFieldsMetaFifo_read;
output  [1023:0] rxEng_dataBuffer3_din;
input   rxEng_dataBuffer3_full_n;
output   rxEng_dataBuffer3_write;
output  [319:0] rxEng_optionalFieldsFifo_din;
input   rxEng_optionalFieldsFifo_full_n;
output   rxEng_optionalFieldsFifo_write;
output  [3:0] rxEng_dataOffsetFifo_din;
input   rxEng_dataOffsetFifo_full_n;
output   rxEng_dataOffsetFifo_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg rxEng_dataBuffer3b_read;
reg rxEng_optionalFieldsMetaFifo_read;
reg[1023:0] rxEng_dataBuffer3_din;
reg rxEng_dataBuffer3_write;
reg[319:0] rxEng_optionalFieldsFifo_din;
reg rxEng_optionalFieldsFifo_write;
reg rxEng_dataOffsetFifo_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire   [1:0] state_V_1_load_load_fu_341_p1;
wire   [0:0] grp_nbreadreq_fu_160_p3;
reg    ap_predicate_op44_read_state1;
wire   [0:0] tmp_i_nbreadreq_fu_174_p3;
reg    ap_predicate_op106_read_state1;
reg    ap_predicate_op109_read_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
reg   [1:0] state_V_1_load_reg_1416;
reg   [1:0] state_V_1_load_reg_1416_pp0_iter1_reg;
reg   [0:0] tmp_i_291_reg_1460;
reg   [0:0] tmp_i_291_reg_1460_pp0_iter1_reg;
reg   [0:0] or_ln582_reg_1608;
reg    ap_predicate_op253_write_state3;
reg   [0:0] icmp_ln870_79_reg_1485;
reg   [0:0] icmp_ln870_79_reg_1485_pp0_iter1_reg;
reg    ap_predicate_op256_write_state3;
reg    ap_predicate_op258_write_state3;
reg   [0:0] tmp_i_reg_1558;
reg   [0:0] tmp_i_reg_1558_pp0_iter1_reg;
reg   [0:0] tmp_54_i_reg_1562;
reg   [0:0] tmp_54_i_reg_1562_pp0_iter1_reg;
reg   [0:0] icmp_ln870_reg_1581;
reg   [0:0] icmp_ln870_reg_1581_pp0_iter1_reg;
reg   [0:0] tmp_syn_V_reg_1571;
reg   [0:0] tmp_syn_V_reg_1571_pp0_iter1_reg;
reg    ap_predicate_op260_write_state3;
reg    ap_predicate_op261_write_state3;
reg    ap_predicate_op262_write_state3;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
reg   [1:0] state_V_1;
reg   [3:0] dataOffset_V;
reg   [319:0] optionalHeader_header_V;
reg   [0:0] optionalHeader_ready;
reg   [15:0] optionalHeader_idx;
reg   [0:0] parseHeader;
reg   [511:0] prevWord_data_V_3;
reg   [63:0] prevWord_keep_V_6;
reg   [0:0] headerWritten;
reg    rxEng_optionalFieldsMetaFifo_blk_n;
wire    ap_block_pp0_stage0;
reg    rxEng_dataBuffer3b_blk_n;
reg    rxEng_dataBuffer3_blk_n;
reg    rxEng_dataOffsetFifo_blk_n;
reg    rxEng_optionalFieldsFifo_blk_n;
reg   [1023:0] reg_336;
reg   [1023:0] reg_336_pp0_iter1_reg;
wire   [0:0] optionalHeader_ready_load_load_fu_349_p1;
reg   [0:0] optionalHeader_ready_load_reg_1420;
reg   [511:0] p_Val2_s_reg_1424;
reg   [63:0] p_Val2_67_reg_1430;
wire   [8:0] shl_ln_fu_365_p3;
reg   [8:0] shl_ln_reg_1436;
wire   [5:0] shl_ln4_fu_383_p3;
reg   [5:0] shl_ln4_reg_1443;
wire   [511:0] xor_ln391_fu_467_p2;
reg   [511:0] xor_ln391_reg_1450;
wire   [63:0] xor_ln391_1_fu_539_p2;
reg   [63:0] xor_ln391_1_reg_1455;
wire   [511:0] tmp_data_V_3_fu_545_p1;
reg   [511:0] tmp_data_V_3_reg_1464;
reg   [63:0] tmp_keep_V_6_reg_1469;
wire   [0:0] icmp_ln414_fu_557_p2;
reg   [0:0] icmp_ln414_reg_1477;
wire   [0:0] icmp_ln870_79_fu_575_p2;
wire   [8:0] shl_ln6_fu_581_p3;
reg   [8:0] shl_ln6_reg_1489;
wire   [9:0] sub_ln599_fu_593_p2;
reg   [9:0] sub_ln599_reg_1496;
wire   [5:0] bvh_d_index_fu_599_p3;
reg   [5:0] bvh_d_index_reg_1501;
wire   [6:0] zext_ln600_fu_607_p1;
reg   [6:0] zext_ln600_reg_1508;
wire   [6:0] sub_ln600_fu_611_p2;
reg   [6:0] sub_ln600_reg_1513;
wire   [9:0] sub_ln674_fu_617_p2;
reg   [9:0] sub_ln674_reg_1519;
wire   [0:0] icmp_ln414_3_fu_635_p2;
reg   [0:0] icmp_ln414_3_reg_1524;
wire   [9:0] sub_ln414_fu_641_p2;
reg   [9:0] sub_ln414_reg_1530;
wire   [511:0] and_ln414_28_fu_689_p2;
reg   [511:0] and_ln414_28_reg_1535;
wire   [0:0] icmp_ln414_4_fu_707_p2;
reg   [0:0] icmp_ln414_4_reg_1541;
wire   [63:0] and_ln414_31_fu_755_p2;
reg   [63:0] and_ln414_31_reg_1547;
wire   [0:0] sendWord_last_V_5_fu_777_p2;
reg   [0:0] sendWord_last_V_5_reg_1553;
reg   [0:0] sendWord_last_V_5_reg_1553_pp0_iter1_reg;
wire   [3:0] trunc_ln145_fu_840_p1;
reg   [3:0] trunc_ln145_reg_1566;
reg   [3:0] trunc_ln145_reg_1566_pp0_iter1_reg;
wire   [0:0] tmp_syn_V_fu_844_p3;
wire   [319:0] tmp_356_fu_862_p1;
reg   [319:0] tmp_356_reg_1575;
reg   [319:0] tmp_356_reg_1575_pp0_iter1_reg;
wire   [0:0] icmp_ln870_fu_872_p2;
wire   [511:0] p_Result_260_fu_1034_p2;
reg   [511:0] p_Result_260_reg_1593;
wire   [63:0] p_Result_261_fu_1039_p2;
reg   [63:0] p_Result_261_reg_1598;
wire   [319:0] p_Result_238_fu_1122_p2;
wire   [0:0] or_ln582_fu_1140_p2;
wire   [511:0] p_Result_253_fu_1290_p2;
reg   [511:0] p_Result_253_reg_1612;
wire   [63:0] p_Result_255_fu_1370_p2;
reg   [63:0] p_Result_255_reg_1617;
reg    ap_block_pp0_stage0_subdone;
reg   [0:0] ap_phi_mux_state_V_3_flag_0_i_phi_fu_212_p18;
wire   [0:0] ap_phi_reg_pp0_iter0_state_V_3_flag_0_i_reg_209;
wire   [0:0] grp_fu_316_p3;
wire   [0:0] or_ln563_fu_890_p2;
reg   [1:0] ap_phi_mux_state_V_3_new_0_i_phi_fu_244_p18;
wire   [1:0] ap_phi_reg_pp0_iter0_state_V_3_new_0_i_reg_241;
wire   [1:0] zext_ln563_fu_896_p1;
wire   [1:0] select_ln566_fu_931_p3;
wire   [1:0] select_ln611_fu_831_p3;
wire   [0:0] ap_phi_reg_pp0_iter0_parseHeader_new_0_i_reg_270;
reg   [0:0] ap_phi_reg_pp0_iter1_parseHeader_new_0_i_reg_270;
wire   [319:0] ap_phi_reg_pp0_iter0_p_015_reg_286;
reg   [319:0] ap_phi_reg_pp0_iter1_p_015_reg_286;
reg   [319:0] ap_phi_reg_pp0_iter2_p_015_reg_286;
wire   [15:0] add_ln67_fu_563_p2;
wire   [511:0] tmp_data_V_fu_852_p1;
wire   [1023:0] zext_ln174_fu_1401_p1;
reg    ap_block_pp0_stage0_01001;
wire   [1023:0] p_08_fu_1406_p5;
wire   [9:0] zext_ln621_fu_373_p1;
wire   [6:0] zext_ln622_fu_391_p1;
wire   [9:0] sub_ln621_fu_377_p2;
wire   [0:0] tmp_fu_401_p3;
wire   [22:0] zext_ln391_fu_409_p1;
wire   [0:0] icmp_ln391_fu_413_p2;
wire   [9:0] sub_ln391_fu_427_p2;
wire   [9:0] select_ln391_fu_419_p3;
wire   [9:0] select_ln391_2_fu_433_p3;
wire   [511:0] zext_ln391_3_fu_441_p1;
wire   [511:0] zext_ln391_4_fu_445_p1;
wire   [511:0] shl_ln391_fu_449_p2;
wire   [511:0] lshr_ln391_fu_455_p2;
wire   [511:0] and_ln391_fu_461_p2;
wire   [6:0] sub_ln622_fu_395_p2;
wire   [0:0] tmp_345_fu_473_p3;
wire   [25:0] zext_ln391_5_fu_481_p1;
wire   [0:0] icmp_ln391_1_fu_485_p2;
wire   [6:0] sub_ln391_1_fu_499_p2;
wire   [6:0] select_ln391_3_fu_491_p3;
wire   [6:0] select_ln391_4_fu_505_p3;
wire   [63:0] zext_ln391_6_fu_513_p1;
wire   [63:0] zext_ln391_7_fu_517_p1;
wire   [63:0] shl_ln391_1_fu_521_p2;
wire   [63:0] lshr_ln391_1_fu_527_p2;
wire   [63:0] and_ln391_3_fu_533_p2;
wire   [24:0] shl_ln5_fu_549_p3;
wire   [9:0] zext_ln599_fu_589_p1;
wire   [0:0] tmp_352_fu_623_p3;
wire   [22:0] zext_ln414_33_fu_631_p1;
wire   [9:0] sub_ln414_14_fu_655_p2;
wire   [9:0] select_ln414_24_fu_647_p3;
wire   [9:0] select_ln414_26_fu_661_p3;
wire   [511:0] zext_ln414_35_fu_669_p1;
wire   [511:0] zext_ln414_36_fu_673_p1;
wire   [511:0] shl_ln414_10_fu_677_p2;
wire   [511:0] lshr_ln414_17_fu_683_p2;
wire   [0:0] tmp_354_fu_695_p3;
wire   [25:0] zext_ln414_37_fu_703_p1;
wire   [6:0] sub_ln414_16_fu_721_p2;
wire   [6:0] select_ln414_28_fu_713_p3;
wire   [6:0] select_ln414_30_fu_727_p3;
wire   [63:0] zext_ln414_39_fu_735_p1;
wire   [63:0] zext_ln414_40_fu_739_p1;
wire   [63:0] shl_ln414_12_fu_743_p2;
wire   [63:0] lshr_ln414_18_fu_749_p2;
wire   [60:0] zext_ln819_1_fu_761_p1;
wire   [60:0] shl_ln819_1_fu_765_p2;
wire   [60:0] grp_fu_306_p4;
wire   [60:0] and_ln819_1_fu_771_p2;
wire   [5:0] bvh_1_fu_789_p3;
wire   [60:0] zext_ln819_2_fu_797_p1;
wire   [60:0] shl_ln819_2_fu_801_p2;
wire   [60:0] and_ln819_2_fu_807_p2;
wire   [0:0] p_Result_s_fu_813_p2;
wire   [0:0] xor_ln874_fu_819_p2;
wire   [0:0] and_ln611_fu_825_p2;
wire   [0:0] xor_ln563_fu_884_p2;
wire   [5:0] bvh_fu_901_p3;
wire   [60:0] zext_ln819_fu_909_p1;
wire   [60:0] shl_ln819_fu_913_p2;
wire   [60:0] and_ln819_fu_919_p2;
wire   [0:0] p_Result_239_fu_925_p2;
wire   [511:0] zext_ln674_fu_958_p1;
wire   [511:0] zext_ln674_19_fu_961_p1;
wire   [511:0] lshr_ln674_fu_964_p2;
wire   [511:0] lshr_ln674_19_fu_969_p2;
wire   [511:0] zext_ln414_fu_981_p1;
wire   [511:0] p_Result_256_fu_975_p2;
wire   [511:0] lshr_ln414_fu_984_p2;
wire   [63:0] zext_ln674_20_fu_996_p1;
wire   [63:0] zext_ln674_21_fu_999_p1;
wire   [63:0] lshr_ln674_20_fu_1002_p2;
wire   [63:0] lshr_ln674_21_fu_1007_p2;
wire   [63:0] zext_ln414_30_fu_1019_p1;
wire   [63:0] p_Result_258_fu_1013_p2;
wire   [63:0] lshr_ln414_14_fu_1022_p2;
wire   [511:0] p_Result_257_fu_990_p2;
wire   [63:0] p_Result_259_fu_1028_p2;
wire   [0:0] trunc_ln414_fu_1048_p1;
wire   [319:0] st_fu_1052_p3;
wire   [319:0] tmp_357_fu_1044_p1;
wire   [319:0] select_ln414_fu_1060_p3;
reg   [319:0] tmp_351_fu_1067_p4;
wire   [319:0] select_ln414_22_fu_1084_p3;
wire   [319:0] select_ln414_23_fu_1091_p3;
wire   [319:0] and_ln414_fu_1098_p2;
wire   [319:0] xor_ln414_fu_1104_p2;
wire   [319:0] select_ln414_21_fu_1077_p3;
wire   [319:0] and_ln414_24_fu_1110_p2;
wire   [319:0] and_ln414_25_fu_1116_p2;
wire   [0:0] xor_ln582_fu_1134_p2;
wire   [511:0] zext_ln674_22_fu_1152_p1;
wire   [511:0] zext_ln674_23_fu_1155_p1;
wire   [511:0] lshr_ln674_22_fu_1158_p2;
wire   [511:0] lshr_ln674_23_fu_1163_p2;
wire   [511:0] zext_ln414_31_fu_1175_p1;
wire   [511:0] p_Result_248_fu_1169_p2;
wire   [511:0] lshr_ln414_15_fu_1178_p2;
wire   [63:0] zext_ln674_24_fu_1190_p1;
wire   [63:0] zext_ln674_25_fu_1193_p1;
wire   [63:0] lshr_ln674_24_fu_1196_p2;
wire   [63:0] lshr_ln674_25_fu_1201_p2;
wire   [63:0] zext_ln414_32_fu_1213_p1;
wire   [63:0] p_Result_250_fu_1207_p2;
wire   [63:0] lshr_ln414_16_fu_1216_p2;
wire   [511:0] zext_ln674_26_fu_1228_p1;
wire   [511:0] lshr_ln674_26_fu_1231_p2;
wire   [9:0] select_ln414_25_fu_1242_p3;
wire   [511:0] p_Result_252_fu_1237_p2;
wire   [511:0] zext_ln414_34_fu_1247_p1;
wire   [511:0] shl_ln414_fu_1251_p2;
reg   [511:0] tmp_353_fu_1257_p4;
wire   [511:0] p_Result_249_fu_1184_p2;
wire   [511:0] xor_ln414_5_fu_1274_p2;
wire   [511:0] select_ln414_27_fu_1267_p3;
wire   [511:0] and_ln414_29_fu_1279_p2;
wire   [511:0] and_ln414_30_fu_1285_p2;
wire   [6:0] sub_ln674_13_fu_1296_p2;
wire   [63:0] zext_ln674_27_fu_1301_p1;
wire   [63:0] lshr_ln674_27_fu_1305_p2;
wire   [6:0] sub_ln414_15_fu_1316_p2;
wire   [6:0] select_ln414_29_fu_1321_p3;
wire   [63:0] p_Result_254_fu_1311_p2;
wire   [63:0] zext_ln414_38_fu_1327_p1;
wire   [63:0] shl_ln414_11_fu_1331_p2;
reg   [63:0] tmp_355_fu_1337_p4;
wire   [63:0] p_Result_251_fu_1222_p2;
wire   [63:0] xor_ln414_6_fu_1354_p2;
wire   [63:0] select_ln414_31_fu_1347_p3;
wire   [63:0] and_ln414_32_fu_1359_p2;
wire   [63:0] and_ln414_33_fu_1365_p2;
wire   [576:0] or_ln_fu_1393_p4;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to1;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_399;
reg    ap_condition_314;
reg    ap_condition_384;
reg    ap_condition_431;
reg    ap_condition_413;
reg    ap_condition_1167;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 state_V_1 = 2'd0;
#0 dataOffset_V = 4'd0;
#0 optionalHeader_header_V = 320'd0;
#0 optionalHeader_ready = 1'd0;
#0 optionalHeader_idx = 16'd0;
#0 parseHeader = 1'd0;
#0 prevWord_data_V_3 = 512'd0;
#0 prevWord_keep_V_6 = 64'd0;
#0 headerWritten = 1'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_i_nbreadreq_fu_174_p3 == 1'd1) & (grp_nbreadreq_fu_160_p3 == 1'd1) & (state_V_1 == 2'd0) & (icmp_ln870_fu_872_p2 == 1'd0) & (tmp_syn_V_fu_844_p3 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter1_parseHeader_new_0_i_reg_270 <= 1'd1;
    end else if ((((tmp_i_nbreadreq_fu_174_p3 == 1'd1) & (grp_nbreadreq_fu_160_p3 == 1'd1) & (state_V_1 == 2'd0) & (icmp_ln870_fu_872_p2 == 1'd0) & (tmp_syn_V_fu_844_p3 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_i_nbreadreq_fu_174_p3 == 1'd1) & (grp_nbreadreq_fu_160_p3 == 1'd1) & (state_V_1 == 2'd0) & (icmp_ln870_fu_872_p2 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        ap_phi_reg_pp0_iter1_parseHeader_new_0_i_reg_270 <= 1'd0;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter1_parseHeader_new_0_i_reg_270 <= ap_phi_reg_pp0_iter0_parseHeader_new_0_i_reg_270;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_384)) begin
        if ((1'b1 == ap_condition_314)) begin
            ap_phi_reg_pp0_iter2_p_015_reg_286 <= p_Result_238_fu_1122_p2;
        end else if ((1'b1 == ap_condition_399)) begin
            ap_phi_reg_pp0_iter2_p_015_reg_286 <= optionalHeader_header_V;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_p_015_reg_286 <= ap_phi_reg_pp0_iter1_p_015_reg_286;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_384)) begin
        if ((1'b1 == ap_condition_413)) begin
            headerWritten <= 1'd0;
        end else if ((1'b1 == ap_condition_431)) begin
            headerWritten <= 1'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_384)) begin
        if ((1'b1 == ap_condition_413)) begin
            optionalHeader_header_V <= tmp_356_reg_1575;
        end else if ((1'b1 == ap_condition_314)) begin
            optionalHeader_header_V <= p_Result_238_fu_1122_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1167)) begin
        if (((tmp_i_nbreadreq_fu_174_p3 == 1'd1) & (state_V_1 == 2'd0))) begin
            optionalHeader_idx <= 16'd1;
        end else if (((state_V_1 == 2'd1) & (optionalHeader_ready_load_load_fu_349_p1 == 1'd0))) begin
            optionalHeader_idx <= add_ln67_fu_563_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1167)) begin
        if (((tmp_i_nbreadreq_fu_174_p3 == 1'd1) & (state_V_1 == 2'd0))) begin
            prevWord_data_V_3 <= tmp_data_V_fu_852_p1;
        end else if ((state_V_1 == 2'd1)) begin
            prevWord_data_V_3 <= tmp_data_V_3_fu_545_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_nbreadreq_fu_160_p3 == 1'd1) & (state_V_1 == 2'd1) & (icmp_ln870_79_fu_575_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        and_ln414_28_reg_1535 <= and_ln414_28_fu_689_p2;
        and_ln414_31_reg_1547 <= and_ln414_31_fu_755_p2;
        bvh_d_index_reg_1501[5 : 2] <= bvh_d_index_fu_599_p3[5 : 2];
        icmp_ln414_3_reg_1524 <= icmp_ln414_3_fu_635_p2;
        icmp_ln414_4_reg_1541 <= icmp_ln414_4_fu_707_p2;
        sendWord_last_V_5_reg_1553 <= sendWord_last_V_5_fu_777_p2;
        shl_ln6_reg_1489[8 : 5] <= shl_ln6_fu_581_p3[8 : 5];
        sub_ln414_reg_1530[9 : 5] <= sub_ln414_fu_641_p2[9 : 5];
        sub_ln599_reg_1496[9 : 5] <= sub_ln599_fu_593_p2[9 : 5];
        sub_ln600_reg_1513[6 : 2] <= sub_ln600_fu_611_p2[6 : 2];
        sub_ln674_reg_1519[9 : 5] <= sub_ln674_fu_617_p2[9 : 5];
        zext_ln600_reg_1508[5 : 2] <= zext_ln600_fu_607_p1[5 : 2];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter1_p_015_reg_286 <= ap_phi_reg_pp0_iter0_p_015_reg_286;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_i_nbreadreq_fu_174_p3 == 1'd1) & (grp_nbreadreq_fu_160_p3 == 1'd1) & (state_V_1 == 2'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        dataOffset_V <= trunc_ln145_fu_840_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_nbreadreq_fu_160_p3 == 1'd1) & (state_V_1 == 2'd1) & (optionalHeader_ready_load_load_fu_349_p1 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln414_reg_1477 <= icmp_ln414_fu_557_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_nbreadreq_fu_160_p3 == 1'd1) & (state_V_1 == 2'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln870_79_reg_1485 <= icmp_ln870_79_fu_575_p2;
        tmp_data_V_3_reg_1464 <= tmp_data_V_3_fu_545_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln870_79_reg_1485_pp0_iter1_reg <= icmp_ln870_79_reg_1485;
        icmp_ln870_reg_1581_pp0_iter1_reg <= icmp_ln870_reg_1581;
        optionalHeader_ready_load_reg_1420 <= optionalHeader_ready;
        p_Val2_67_reg_1430 <= prevWord_keep_V_6;
        p_Val2_s_reg_1424 <= prevWord_data_V_3;
        reg_336_pp0_iter1_reg <= reg_336;
        sendWord_last_V_5_reg_1553_pp0_iter1_reg <= sendWord_last_V_5_reg_1553;
        state_V_1_load_reg_1416 <= state_V_1;
        state_V_1_load_reg_1416_pp0_iter1_reg <= state_V_1_load_reg_1416;
        tmp_356_reg_1575_pp0_iter1_reg <= tmp_356_reg_1575;
        tmp_54_i_reg_1562_pp0_iter1_reg <= tmp_54_i_reg_1562;
        tmp_i_291_reg_1460_pp0_iter1_reg <= tmp_i_291_reg_1460;
        tmp_i_reg_1558_pp0_iter1_reg <= tmp_i_reg_1558;
        tmp_syn_V_reg_1571_pp0_iter1_reg <= tmp_syn_V_reg_1571;
        trunc_ln145_reg_1566_pp0_iter1_reg <= trunc_ln145_reg_1566;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_i_nbreadreq_fu_174_p3 == 1'd1) & (grp_nbreadreq_fu_160_p3 == 1'd1) & (state_V_1 == 2'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln870_reg_1581 <= icmp_ln870_fu_872_p2;
        tmp_356_reg_1575 <= tmp_356_fu_862_p1;
        tmp_syn_V_reg_1571 <= rxEng_optionalFieldsMetaFifo_dout[32'd8];
        trunc_ln145_reg_1566 <= trunc_ln145_fu_840_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((((tmp_i_nbreadreq_fu_174_p3 == 1'd1) & (grp_nbreadreq_fu_160_p3 == 1'd1) & (state_V_1 == 2'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((grp_nbreadreq_fu_160_p3 == 1'd1) & (state_V_1 == 2'd1) & (ap_start == 1'b1) & (optionalHeader_ready_load_load_fu_349_p1 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        optionalHeader_ready <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_i_291_reg_1460 == 1'd1) & (state_V_1_load_reg_1416 == 2'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        or_ln582_reg_1608 <= or_ln582_fu_1140_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_i_291_reg_1460 == 1'd1) & (state_V_1_load_reg_1416 == 2'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln870_79_reg_1485 == 1'd0))) begin
        p_Result_253_reg_1612 <= p_Result_253_fu_1290_p2;
        p_Result_255_reg_1617 <= p_Result_255_fu_1370_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((state_V_1_load_reg_1416 == 2'd2) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_Result_260_reg_1593 <= p_Result_260_fu_1034_p2;
        p_Result_261_reg_1598 <= p_Result_261_fu_1039_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((state_V_1_load_reg_1416 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_54_i_reg_1562 == 1'd1) & (tmp_i_reg_1558 == 1'd1))) begin
        parseHeader <= ap_phi_reg_pp0_iter1_parseHeader_new_0_i_reg_270;
    end
end

always @ (posedge ap_clk) begin
    if ((((tmp_i_nbreadreq_fu_174_p3 == 1'd1) & (grp_nbreadreq_fu_160_p3 == 1'd1) & (state_V_1 == 2'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((grp_nbreadreq_fu_160_p3 == 1'd1) & (state_V_1 == 2'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        prevWord_keep_V_6 <= {{rxEng_dataBuffer3b_dout[575:512]}};
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_predicate_op109_read_state1 == 1'b1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_predicate_op44_read_state1 == 1'b1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        reg_336 <= rxEng_dataBuffer3b_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((state_V_1_load_load_fu_341_p1 == 2'd2) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        shl_ln4_reg_1443[5 : 2] <= shl_ln4_fu_383_p3[5 : 2];
        shl_ln_reg_1436[8 : 5] <= shl_ln_fu_365_p3[8 : 5];
        xor_ln391_1_reg_1455 <= xor_ln391_1_fu_539_p2;
        xor_ln391_reg_1450 <= xor_ln391_fu_467_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_state_V_3_flag_0_i_phi_fu_212_p18 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        state_V_1 <= ap_phi_mux_state_V_3_new_0_i_phi_fu_244_p18;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_i_nbreadreq_fu_174_p3 == 1'd1) & (state_V_1 == 2'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_54_i_reg_1562 <= grp_nbreadreq_fu_160_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((state_V_1 == 2'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_i_291_reg_1460 <= grp_nbreadreq_fu_160_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((state_V_1 == 2'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_i_reg_1558 <= tmp_i_nbreadreq_fu_174_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_nbreadreq_fu_160_p3 == 1'd1) & (state_V_1 == 2'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_keep_V_6_reg_1469 <= {{rxEng_dataBuffer3b_dout[575:512]}};
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to1 = 1'b1;
    end else begin
        ap_idle_pp0_0to1 = 1'b0;
    end
end

always @ (*) begin
    if (((state_V_1_load_load_fu_341_p1 == 2'd2) | ((tmp_i_nbreadreq_fu_174_p3 == 1'd1) & (grp_nbreadreq_fu_160_p3 == 1'd1) & (state_V_1 == 2'd0) & (or_ln563_fu_890_p2 == 1'd0)) | ((tmp_i_nbreadreq_fu_174_p3 == 1'd1) & (grp_nbreadreq_fu_160_p3 == 1'd1) & (state_V_1 == 2'd0) & (or_ln563_fu_890_p2 == 1'd1)) | ((grp_nbreadreq_fu_160_p3 == 1'd1) & (state_V_1 == 2'd1) & (grp_fu_316_p3 == 1'd1)))) begin
        ap_phi_mux_state_V_3_flag_0_i_phi_fu_212_p18 = 1'd1;
    end else if (((state_V_1_load_load_fu_341_p1 == 2'd3) | ((tmp_i_nbreadreq_fu_174_p3 == 1'd1) & (grp_nbreadreq_fu_160_p3 == 1'd0) & (state_V_1 == 2'd0)) | ((grp_nbreadreq_fu_160_p3 == 1'd1) & (state_V_1 == 2'd1) & (grp_fu_316_p3 == 1'd0)) | ((tmp_i_nbreadreq_fu_174_p3 == 1'd0) & (state_V_1 == 2'd0)) | ((grp_nbreadreq_fu_160_p3 == 1'd0) & (state_V_1 == 2'd1)))) begin
        ap_phi_mux_state_V_3_flag_0_i_phi_fu_212_p18 = 1'd0;
    end else begin
        ap_phi_mux_state_V_3_flag_0_i_phi_fu_212_p18 = ap_phi_reg_pp0_iter0_state_V_3_flag_0_i_reg_209;
    end
end

always @ (*) begin
    if (((grp_nbreadreq_fu_160_p3 == 1'd1) & (state_V_1 == 2'd1) & (grp_fu_316_p3 == 1'd1))) begin
        ap_phi_mux_state_V_3_new_0_i_phi_fu_244_p18 = select_ln611_fu_831_p3;
    end else if (((tmp_i_nbreadreq_fu_174_p3 == 1'd1) & (grp_nbreadreq_fu_160_p3 == 1'd1) & (state_V_1 == 2'd0) & (or_ln563_fu_890_p2 == 1'd0))) begin
        ap_phi_mux_state_V_3_new_0_i_phi_fu_244_p18 = select_ln566_fu_931_p3;
    end else if (((tmp_i_nbreadreq_fu_174_p3 == 1'd1) & (grp_nbreadreq_fu_160_p3 == 1'd1) & (state_V_1 == 2'd0) & (or_ln563_fu_890_p2 == 1'd1))) begin
        ap_phi_mux_state_V_3_new_0_i_phi_fu_244_p18 = zext_ln563_fu_896_p1;
    end else if ((state_V_1_load_load_fu_341_p1 == 2'd2)) begin
        ap_phi_mux_state_V_3_new_0_i_phi_fu_244_p18 = 2'd0;
    end else begin
        ap_phi_mux_state_V_3_new_0_i_phi_fu_244_p18 = ap_phi_reg_pp0_iter0_state_V_3_new_0_i_reg_241;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to1 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((((state_V_1_load_reg_1416_pp0_iter1_reg == 2'd2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_predicate_op262_write_state3 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_predicate_op258_write_state3 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_predicate_op256_write_state3 == 1'b1)))) begin
        rxEng_dataBuffer3_blk_n = rxEng_dataBuffer3_full_n;
    end else begin
        rxEng_dataBuffer3_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_01001) & (ap_predicate_op262_write_state3 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_01001) & (ap_predicate_op258_write_state3 == 1'b1)))) begin
        rxEng_dataBuffer3_din = reg_336_pp0_iter1_reg;
    end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_01001) & (ap_predicate_op256_write_state3 == 1'b1))) begin
        rxEng_dataBuffer3_din = p_08_fu_1406_p5;
    end else if (((state_V_1_load_reg_1416_pp0_iter1_reg == 2'd2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_01001))) begin
        rxEng_dataBuffer3_din = zext_ln174_fu_1401_p1;
    end else begin
        rxEng_dataBuffer3_din = 'bx;
    end
end

always @ (*) begin
    if ((((state_V_1_load_reg_1416_pp0_iter1_reg == 2'd2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op262_write_state3 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op258_write_state3 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op256_write_state3 == 1'b1)))) begin
        rxEng_dataBuffer3_write = 1'b1;
    end else begin
        rxEng_dataBuffer3_write = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_op109_read_state1 == 1'b1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (ap_done_reg == 1'b0)) | ((ap_predicate_op44_read_state1 == 1'b1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (ap_done_reg == 1'b0)))) begin
        rxEng_dataBuffer3b_blk_n = rxEng_dataBuffer3b_empty_n;
    end else begin
        rxEng_dataBuffer3b_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_predicate_op109_read_state1 == 1'b1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_predicate_op44_read_state1 == 1'b1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        rxEng_dataBuffer3b_read = 1'b1;
    end else begin
        rxEng_dataBuffer3b_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_predicate_op260_write_state3 == 1'b1))) begin
        rxEng_dataOffsetFifo_blk_n = rxEng_dataOffsetFifo_full_n;
    end else begin
        rxEng_dataOffsetFifo_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op260_write_state3 == 1'b1))) begin
        rxEng_dataOffsetFifo_write = 1'b1;
    end else begin
        rxEng_dataOffsetFifo_write = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_predicate_op261_write_state3 == 1'b1)) | ((ap_predicate_op253_write_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0)))) begin
        rxEng_optionalFieldsFifo_blk_n = rxEng_optionalFieldsFifo_full_n;
    end else begin
        rxEng_optionalFieldsFifo_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_01001))) begin
        if ((ap_predicate_op261_write_state3 == 1'b1)) begin
            rxEng_optionalFieldsFifo_din = tmp_356_reg_1575_pp0_iter1_reg;
        end else if ((ap_predicate_op253_write_state3 == 1'b1)) begin
            rxEng_optionalFieldsFifo_din = ap_phi_reg_pp0_iter2_p_015_reg_286;
        end else begin
            rxEng_optionalFieldsFifo_din = 'bx;
        end
    end else begin
        rxEng_optionalFieldsFifo_din = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op261_write_state3 == 1'b1)) | ((ap_predicate_op253_write_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        rxEng_optionalFieldsFifo_write = 1'b1;
    end else begin
        rxEng_optionalFieldsFifo_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op106_read_state1 == 1'b1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (ap_done_reg == 1'b0))) begin
        rxEng_optionalFieldsMetaFifo_blk_n = rxEng_optionalFieldsMetaFifo_empty_n;
    end else begin
        rxEng_optionalFieldsMetaFifo_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op106_read_state1 == 1'b1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rxEng_optionalFieldsMetaFifo_read = 1'b1;
    end else begin
        rxEng_optionalFieldsMetaFifo_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln67_fu_563_p2 = (optionalHeader_idx + 16'd1);

assign and_ln391_3_fu_533_p2 = (shl_ln391_1_fu_521_p2 & lshr_ln391_1_fu_527_p2);

assign and_ln391_fu_461_p2 = (shl_ln391_fu_449_p2 & lshr_ln391_fu_455_p2);

assign and_ln414_24_fu_1110_p2 = (xor_ln414_fu_1104_p2 & optionalHeader_header_V);

assign and_ln414_25_fu_1116_p2 = (select_ln414_21_fu_1077_p3 & and_ln414_fu_1098_p2);

assign and_ln414_28_fu_689_p2 = (shl_ln414_10_fu_677_p2 & lshr_ln414_17_fu_683_p2);

assign and_ln414_29_fu_1279_p2 = (xor_ln414_5_fu_1274_p2 & p_Result_249_fu_1184_p2);

assign and_ln414_30_fu_1285_p2 = (select_ln414_27_fu_1267_p3 & and_ln414_28_reg_1535);

assign and_ln414_31_fu_755_p2 = (shl_ln414_12_fu_743_p2 & lshr_ln414_18_fu_749_p2);

assign and_ln414_32_fu_1359_p2 = (xor_ln414_6_fu_1354_p2 & p_Result_251_fu_1222_p2);

assign and_ln414_33_fu_1365_p2 = (select_ln414_31_fu_1347_p3 & and_ln414_31_reg_1547);

assign and_ln414_fu_1098_p2 = (select_ln414_23_fu_1091_p3 & select_ln414_22_fu_1084_p3);

assign and_ln611_fu_825_p2 = (xor_ln874_fu_819_p2 & p_Result_s_fu_813_p2);

assign and_ln819_1_fu_771_p2 = (shl_ln819_1_fu_765_p2 & grp_fu_306_p4);

assign and_ln819_2_fu_807_p2 = (shl_ln819_2_fu_801_p2 & grp_fu_306_p4);

assign and_ln819_fu_919_p2 = (shl_ln819_fu_913_p2 & grp_fu_306_p4);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & ((ap_done_reg == 1'b1) | ((ap_predicate_op109_read_state1 == 1'b1) & (rxEng_dataBuffer3b_empty_n == 1'b0)) | ((ap_predicate_op106_read_state1 == 1'b1) & (rxEng_optionalFieldsMetaFifo_empty_n == 1'b0)) | ((ap_predicate_op44_read_state1 == 1'b1) & (rxEng_dataBuffer3b_empty_n == 1'b0)))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (((rxEng_optionalFieldsFifo_full_n == 1'b0) & (ap_predicate_op261_write_state3 == 1'b1)) | ((state_V_1_load_reg_1416_pp0_iter1_reg == 2'd2) & (rxEng_dataBuffer3_full_n == 1'b0)) | ((rxEng_dataBuffer3_full_n == 1'b0) & (ap_predicate_op262_write_state3 == 1'b1)) | ((rxEng_dataBuffer3_full_n == 1'b0) & (ap_predicate_op258_write_state3 == 1'b1)) | ((rxEng_dataBuffer3_full_n == 1'b0) & (ap_predicate_op256_write_state3 == 1'b1)) | ((ap_predicate_op260_write_state3 == 1'b1) & (rxEng_dataOffsetFifo_full_n == 1'b0)) | ((ap_predicate_op253_write_state3 == 1'b1) & (rxEng_optionalFieldsFifo_full_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & ((ap_done_reg == 1'b1) | ((ap_predicate_op109_read_state1 == 1'b1) & (rxEng_dataBuffer3b_empty_n == 1'b0)) | ((ap_predicate_op106_read_state1 == 1'b1) & (rxEng_optionalFieldsMetaFifo_empty_n == 1'b0)) | ((ap_predicate_op44_read_state1 == 1'b1) & (rxEng_dataBuffer3b_empty_n == 1'b0)))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (((rxEng_optionalFieldsFifo_full_n == 1'b0) & (ap_predicate_op261_write_state3 == 1'b1)) | ((state_V_1_load_reg_1416_pp0_iter1_reg == 2'd2) & (rxEng_dataBuffer3_full_n == 1'b0)) | ((rxEng_dataBuffer3_full_n == 1'b0) & (ap_predicate_op262_write_state3 == 1'b1)) | ((rxEng_dataBuffer3_full_n == 1'b0) & (ap_predicate_op258_write_state3 == 1'b1)) | ((rxEng_dataBuffer3_full_n == 1'b0) & (ap_predicate_op256_write_state3 == 1'b1)) | ((ap_predicate_op260_write_state3 == 1'b1) & (rxEng_dataOffsetFifo_full_n == 1'b0)) | ((ap_predicate_op253_write_state3 == 1'b1) & (rxEng_optionalFieldsFifo_full_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & ((ap_done_reg == 1'b1) | ((ap_predicate_op109_read_state1 == 1'b1) & (rxEng_dataBuffer3b_empty_n == 1'b0)) | ((ap_predicate_op106_read_state1 == 1'b1) & (rxEng_optionalFieldsMetaFifo_empty_n == 1'b0)) | ((ap_predicate_op44_read_state1 == 1'b1) & (rxEng_dataBuffer3b_empty_n == 1'b0)))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (((rxEng_optionalFieldsFifo_full_n == 1'b0) & (ap_predicate_op261_write_state3 == 1'b1)) | ((state_V_1_load_reg_1416_pp0_iter1_reg == 2'd2) & (rxEng_dataBuffer3_full_n == 1'b0)) | ((rxEng_dataBuffer3_full_n == 1'b0) & (ap_predicate_op262_write_state3 == 1'b1)) | ((rxEng_dataBuffer3_full_n == 1'b0) & (ap_predicate_op258_write_state3 == 1'b1)) | ((rxEng_dataBuffer3_full_n == 1'b0) & (ap_predicate_op256_write_state3 == 1'b1)) | ((ap_predicate_op260_write_state3 == 1'b1) & (rxEng_dataOffsetFifo_full_n == 1'b0)) | ((ap_predicate_op253_write_state3 == 1'b1) & (rxEng_optionalFieldsFifo_full_n == 1'b0)))));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_done_reg == 1'b1) | ((ap_predicate_op109_read_state1 == 1'b1) & (rxEng_dataBuffer3b_empty_n == 1'b0)) | ((ap_predicate_op106_read_state1 == 1'b1) & (rxEng_optionalFieldsMetaFifo_empty_n == 1'b0)) | ((ap_predicate_op44_read_state1 == 1'b1) & (rxEng_dataBuffer3b_empty_n == 1'b0)));
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = (((rxEng_optionalFieldsFifo_full_n == 1'b0) & (ap_predicate_op261_write_state3 == 1'b1)) | ((state_V_1_load_reg_1416_pp0_iter1_reg == 2'd2) & (rxEng_dataBuffer3_full_n == 1'b0)) | ((rxEng_dataBuffer3_full_n == 1'b0) & (ap_predicate_op262_write_state3 == 1'b1)) | ((rxEng_dataBuffer3_full_n == 1'b0) & (ap_predicate_op258_write_state3 == 1'b1)) | ((rxEng_dataBuffer3_full_n == 1'b0) & (ap_predicate_op256_write_state3 == 1'b1)) | ((ap_predicate_op260_write_state3 == 1'b1) & (rxEng_dataOffsetFifo_full_n == 1'b0)) | ((ap_predicate_op253_write_state3 == 1'b1) & (rxEng_optionalFieldsFifo_full_n == 1'b0)));
end

always @ (*) begin
    ap_condition_1167 = ((grp_nbreadreq_fu_160_p3 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001));
end

always @ (*) begin
    ap_condition_314 = ((tmp_i_291_reg_1460 == 1'd1) & (state_V_1_load_reg_1416 == 2'd1) & (optionalHeader_ready_load_reg_1420 == 1'd0));
end

always @ (*) begin
    ap_condition_384 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001));
end

always @ (*) begin
    ap_condition_399 = ((tmp_i_291_reg_1460 == 1'd1) & (state_V_1_load_reg_1416 == 2'd1) & (optionalHeader_ready_load_reg_1420 == 1'd1));
end

always @ (*) begin
    ap_condition_413 = ((state_V_1_load_reg_1416 == 2'd0) & (tmp_54_i_reg_1562 == 1'd1) & (tmp_i_reg_1558 == 1'd1));
end

always @ (*) begin
    ap_condition_431 = ((tmp_i_291_reg_1460 == 1'd1) & (state_V_1_load_reg_1416 == 2'd1) & (or_ln582_fu_1140_p2 == 1'd0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_phi_reg_pp0_iter0_p_015_reg_286 = 'bx;

assign ap_phi_reg_pp0_iter0_parseHeader_new_0_i_reg_270 = 'bx;

assign ap_phi_reg_pp0_iter0_state_V_3_flag_0_i_reg_209 = 'bx;

assign ap_phi_reg_pp0_iter0_state_V_3_new_0_i_reg_241 = 'bx;

always @ (*) begin
    ap_predicate_op106_read_state1 = ((tmp_i_nbreadreq_fu_174_p3 == 1'd1) & (grp_nbreadreq_fu_160_p3 == 1'd1) & (state_V_1 == 2'd0));
end

always @ (*) begin
    ap_predicate_op109_read_state1 = ((tmp_i_nbreadreq_fu_174_p3 == 1'd1) & (grp_nbreadreq_fu_160_p3 == 1'd1) & (state_V_1 == 2'd0));
end

always @ (*) begin
    ap_predicate_op253_write_state3 = ((or_ln582_reg_1608 == 1'd0) & (tmp_i_291_reg_1460_pp0_iter1_reg == 1'd1) & (state_V_1_load_reg_1416_pp0_iter1_reg == 2'd1));
end

always @ (*) begin
    ap_predicate_op256_write_state3 = ((tmp_i_291_reg_1460_pp0_iter1_reg == 1'd1) & (state_V_1_load_reg_1416_pp0_iter1_reg == 2'd1) & (icmp_ln870_79_reg_1485_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op258_write_state3 = ((tmp_i_291_reg_1460_pp0_iter1_reg == 1'd1) & (state_V_1_load_reg_1416_pp0_iter1_reg == 2'd1) & (icmp_ln870_79_reg_1485_pp0_iter1_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op260_write_state3 = ((state_V_1_load_reg_1416_pp0_iter1_reg == 2'd0) & (tmp_syn_V_reg_1571_pp0_iter1_reg == 1'd1) & (icmp_ln870_reg_1581_pp0_iter1_reg == 1'd0) & (tmp_54_i_reg_1562_pp0_iter1_reg == 1'd1) & (tmp_i_reg_1558_pp0_iter1_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op261_write_state3 = ((state_V_1_load_reg_1416_pp0_iter1_reg == 2'd0) & (tmp_syn_V_reg_1571_pp0_iter1_reg == 1'd1) & (icmp_ln870_reg_1581_pp0_iter1_reg == 1'd0) & (tmp_54_i_reg_1562_pp0_iter1_reg == 1'd1) & (tmp_i_reg_1558_pp0_iter1_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op262_write_state3 = ((state_V_1_load_reg_1416_pp0_iter1_reg == 2'd0) & (icmp_ln870_reg_1581_pp0_iter1_reg == 1'd1) & (tmp_54_i_reg_1562_pp0_iter1_reg == 1'd1) & (tmp_i_reg_1558_pp0_iter1_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op44_read_state1 = ((grp_nbreadreq_fu_160_p3 == 1'd1) & (state_V_1 == 2'd1));
end

assign bvh_1_fu_789_p3 = {{dataOffset_V}, {2'd0}};

assign bvh_d_index_fu_599_p3 = {{dataOffset_V}, {2'd0}};

assign bvh_fu_901_p3 = {{trunc_ln145_fu_840_p1}, {2'd0}};

assign grp_fu_306_p4 = {{rxEng_dataBuffer3b_dout[572:512]}};

assign grp_fu_316_p3 = rxEng_dataBuffer3b_dout[32'd576];

assign grp_nbreadreq_fu_160_p3 = rxEng_dataBuffer3b_empty_n;

assign icmp_ln391_1_fu_485_p2 = ((zext_ln391_5_fu_481_p1 != 26'd0) ? 1'b1 : 1'b0);

assign icmp_ln391_fu_413_p2 = ((zext_ln391_fu_409_p1 != 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln414_3_fu_635_p2 = ((zext_ln414_33_fu_631_p1 != 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln414_4_fu_707_p2 = ((zext_ln414_37_fu_703_p1 != 26'd0) ? 1'b1 : 1'b0);

assign icmp_ln414_fu_557_p2 = ((shl_ln5_fu_549_p3 > 25'd319) ? 1'b1 : 1'b0);

assign icmp_ln870_79_fu_575_p2 = ((dataOffset_V == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln870_fu_872_p2 = ((trunc_ln145_fu_840_p1 == 4'd0) ? 1'b1 : 1'b0);

assign lshr_ln391_1_fu_527_p2 = 64'd18446744073709551615 >> zext_ln391_7_fu_517_p1;

assign lshr_ln391_fu_455_p2 = 512'd13407807929942597099574024998205846127479365820592393377723561443721764030073546976801874298166903427690031858186486050853753882811946569946433649006084095 >> zext_ln391_4_fu_445_p1;

assign lshr_ln414_14_fu_1022_p2 = 64'd18446744073709551615 >> zext_ln414_30_fu_1019_p1;

assign lshr_ln414_15_fu_1178_p2 = 512'd13407807929942597099574024998205846127479365820592393377723561443721764030073546976801874298166903427690031858186486050853753882811946569946433649006084095 >> zext_ln414_31_fu_1175_p1;

assign lshr_ln414_16_fu_1216_p2 = 64'd18446744073709551615 >> zext_ln414_32_fu_1213_p1;

assign lshr_ln414_17_fu_683_p2 = 512'd13407807929942597099574024998205846127479365820592393377723561443721764030073546976801874298166903427690031858186486050853753882811946569946433649006084095 >> zext_ln414_36_fu_673_p1;

assign lshr_ln414_18_fu_749_p2 = 64'd18446744073709551615 >> zext_ln414_40_fu_739_p1;

assign lshr_ln414_fu_984_p2 = 512'd13407807929942597099574024998205846127479365820592393377723561443721764030073546976801874298166903427690031858186486050853753882811946569946433649006084095 >> zext_ln414_fu_981_p1;

assign lshr_ln674_19_fu_969_p2 = 512'd13407807929942597099574024998205846127479365820592393377723561443721764030073546976801874298166903427690031858186486050853753882811946569946433649006084095 >> zext_ln674_19_fu_961_p1;

assign lshr_ln674_20_fu_1002_p2 = p_Val2_67_reg_1430 >> zext_ln674_20_fu_996_p1;

assign lshr_ln674_21_fu_1007_p2 = 64'd18446744073709551615 >> zext_ln674_21_fu_999_p1;

assign lshr_ln674_22_fu_1158_p2 = p_Val2_s_reg_1424 >> zext_ln674_22_fu_1152_p1;

assign lshr_ln674_23_fu_1163_p2 = 512'd13407807929942597099574024998205846127479365820592393377723561443721764030073546976801874298166903427690031858186486050853753882811946569946433649006084095 >> zext_ln674_23_fu_1155_p1;

assign lshr_ln674_24_fu_1196_p2 = p_Val2_67_reg_1430 >> zext_ln674_24_fu_1190_p1;

assign lshr_ln674_25_fu_1201_p2 = 64'd18446744073709551615 >> zext_ln674_25_fu_1193_p1;

assign lshr_ln674_26_fu_1231_p2 = 512'd13407807929942597099574024998205846127479365820592393377723561443721764030073546976801874298166903427690031858186486050853753882811946569946433649006084095 >> zext_ln674_26_fu_1228_p1;

assign lshr_ln674_27_fu_1305_p2 = 64'd18446744073709551615 >> zext_ln674_27_fu_1301_p1;

assign lshr_ln674_fu_964_p2 = p_Val2_s_reg_1424 >> zext_ln674_fu_958_p1;

assign optionalHeader_ready_load_load_fu_349_p1 = optionalHeader_ready;

assign or_ln563_fu_890_p2 = (xor_ln563_fu_884_p2 | icmp_ln870_fu_872_p2);

assign or_ln582_fu_1140_p2 = (xor_ln582_fu_1134_p2 | headerWritten);

assign or_ln_fu_1393_p4 = {{{{1'd1}, {p_Result_261_reg_1598}}}, {p_Result_260_reg_1593}};

assign p_08_fu_1406_p5 = {{{{{{447'd0}, {sendWord_last_V_5_reg_1553_pp0_iter1_reg}}}, {p_Result_255_reg_1617}}}, {p_Result_253_reg_1612}};

assign p_Result_238_fu_1122_p2 = (and_ln414_25_fu_1116_p2 | and_ln414_24_fu_1110_p2);

assign p_Result_239_fu_925_p2 = ((and_ln819_fu_919_p2 == 61'd0) ? 1'b1 : 1'b0);

assign p_Result_248_fu_1169_p2 = (lshr_ln674_23_fu_1163_p2 & lshr_ln674_22_fu_1158_p2);

assign p_Result_249_fu_1184_p2 = (p_Result_248_fu_1169_p2 & lshr_ln414_15_fu_1178_p2);

assign p_Result_250_fu_1207_p2 = (lshr_ln674_25_fu_1201_p2 & lshr_ln674_24_fu_1196_p2);

assign p_Result_251_fu_1222_p2 = (p_Result_250_fu_1207_p2 & lshr_ln414_16_fu_1216_p2);

assign p_Result_252_fu_1237_p2 = (tmp_data_V_3_reg_1464 & lshr_ln674_26_fu_1231_p2);

assign p_Result_253_fu_1290_p2 = (and_ln414_30_fu_1285_p2 | and_ln414_29_fu_1279_p2);

assign p_Result_254_fu_1311_p2 = (tmp_keep_V_6_reg_1469 & lshr_ln674_27_fu_1305_p2);

assign p_Result_255_fu_1370_p2 = (and_ln414_33_fu_1365_p2 | and_ln414_32_fu_1359_p2);

assign p_Result_256_fu_975_p2 = (lshr_ln674_fu_964_p2 & lshr_ln674_19_fu_969_p2);

assign p_Result_257_fu_990_p2 = (p_Result_256_fu_975_p2 & lshr_ln414_fu_984_p2);

assign p_Result_258_fu_1013_p2 = (lshr_ln674_21_fu_1007_p2 & lshr_ln674_20_fu_1002_p2);

assign p_Result_259_fu_1028_p2 = (p_Result_258_fu_1013_p2 & lshr_ln414_14_fu_1022_p2);

assign p_Result_260_fu_1034_p2 = (xor_ln391_reg_1450 & p_Result_257_fu_990_p2);

assign p_Result_261_fu_1039_p2 = (xor_ln391_1_reg_1455 & p_Result_259_fu_1028_p2);

assign p_Result_s_fu_813_p2 = ((and_ln819_2_fu_807_p2 != 61'd0) ? 1'b1 : 1'b0);

assign rxEng_dataOffsetFifo_din = trunc_ln145_reg_1566_pp0_iter1_reg;

assign select_ln391_2_fu_433_p3 = ((icmp_ln391_fu_413_p2[0:0] == 1'b1) ? sub_ln391_fu_427_p2 : 10'd0);

assign select_ln391_3_fu_491_p3 = ((icmp_ln391_1_fu_485_p2[0:0] == 1'b1) ? 7'd63 : sub_ln622_fu_395_p2);

assign select_ln391_4_fu_505_p3 = ((icmp_ln391_1_fu_485_p2[0:0] == 1'b1) ? sub_ln391_1_fu_499_p2 : 7'd0);

assign select_ln391_fu_419_p3 = ((icmp_ln391_fu_413_p2[0:0] == 1'b1) ? 10'd511 : sub_ln621_fu_377_p2);

assign select_ln414_21_fu_1077_p3 = ((icmp_ln414_reg_1477[0:0] == 1'b1) ? tmp_351_fu_1067_p4 : tmp_357_fu_1044_p1);

assign select_ln414_22_fu_1084_p3 = ((icmp_ln414_reg_1477[0:0] == 1'b1) ? 320'd1067993517960455041197510853084776057301352261178326384973520803911109862890320275011481043468288 : 320'd2135987035920910082395021706169552114602704522356652769947041607822219725780640550022962086936575);

assign select_ln414_23_fu_1091_p3 = ((icmp_ln414_reg_1477[0:0] == 1'b1) ? 320'd1 : 320'd2135987035920910082395021706169552114602704522356652769947041607822219725780640550022962086936575);

assign select_ln414_24_fu_647_p3 = ((icmp_ln414_3_fu_635_p2[0:0] == 1'b1) ? 10'd511 : sub_ln599_fu_593_p2);

assign select_ln414_25_fu_1242_p3 = ((icmp_ln414_3_reg_1524[0:0] == 1'b1) ? sub_ln414_reg_1530 : sub_ln599_reg_1496);

assign select_ln414_26_fu_661_p3 = ((icmp_ln414_3_fu_635_p2[0:0] == 1'b1) ? sub_ln414_14_fu_655_p2 : 10'd0);

assign select_ln414_27_fu_1267_p3 = ((icmp_ln414_3_reg_1524[0:0] == 1'b1) ? tmp_353_fu_1257_p4 : shl_ln414_fu_1251_p2);

assign select_ln414_28_fu_713_p3 = ((icmp_ln414_4_fu_707_p2[0:0] == 1'b1) ? 7'd63 : sub_ln600_fu_611_p2);

assign select_ln414_29_fu_1321_p3 = ((icmp_ln414_4_reg_1541[0:0] == 1'b1) ? sub_ln414_15_fu_1316_p2 : sub_ln600_reg_1513);

assign select_ln414_30_fu_727_p3 = ((icmp_ln414_4_fu_707_p2[0:0] == 1'b1) ? sub_ln414_16_fu_721_p2 : 7'd0);

assign select_ln414_31_fu_1347_p3 = ((icmp_ln414_4_reg_1541[0:0] == 1'b1) ? tmp_355_fu_1337_p4 : shl_ln414_11_fu_1331_p2);

assign select_ln414_fu_1060_p3 = ((icmp_ln414_reg_1477[0:0] == 1'b1) ? st_fu_1052_p3 : tmp_357_fu_1044_p1);

assign select_ln566_fu_931_p3 = ((p_Result_239_fu_925_p2[0:0] == 1'b1) ? 2'd0 : 2'd2);

assign select_ln611_fu_831_p3 = ((and_ln611_fu_825_p2[0:0] == 1'b1) ? 2'd2 : 2'd0);

assign sendWord_last_V_5_fu_777_p2 = ((and_ln819_1_fu_771_p2 == 61'd0) ? 1'b1 : 1'b0);

assign shl_ln391_1_fu_521_p2 = 64'd18446744073709551615 << zext_ln391_6_fu_513_p1;

assign shl_ln391_fu_449_p2 = 512'd13407807929942597099574024998205846127479365820592393377723561443721764030073546976801874298166903427690031858186486050853753882811946569946433649006084095 << zext_ln391_3_fu_441_p1;

assign shl_ln414_10_fu_677_p2 = 512'd13407807929942597099574024998205846127479365820592393377723561443721764030073546976801874298166903427690031858186486050853753882811946569946433649006084095 << zext_ln414_35_fu_669_p1;

assign shl_ln414_11_fu_1331_p2 = p_Result_254_fu_1311_p2 << zext_ln414_38_fu_1327_p1;

assign shl_ln414_12_fu_743_p2 = 64'd18446744073709551615 << zext_ln414_39_fu_735_p1;

assign shl_ln414_fu_1251_p2 = p_Result_252_fu_1237_p2 << zext_ln414_34_fu_1247_p1;

assign shl_ln4_fu_383_p3 = {{dataOffset_V}, {2'd0}};

assign shl_ln5_fu_549_p3 = {{optionalHeader_idx}, {9'd0}};

assign shl_ln6_fu_581_p3 = {{dataOffset_V}, {5'd0}};

assign shl_ln819_1_fu_765_p2 = 61'd1 << zext_ln819_1_fu_761_p1;

assign shl_ln819_2_fu_801_p2 = 61'd1 << zext_ln819_2_fu_797_p1;

assign shl_ln819_fu_913_p2 = 61'd1 << zext_ln819_fu_909_p1;

assign shl_ln_fu_365_p3 = {{dataOffset_V}, {5'd0}};

assign st_fu_1052_p3 = {{trunc_ln414_fu_1048_p1}, {319'd0}};

assign state_V_1_load_load_fu_341_p1 = state_V_1;

assign sub_ln391_1_fu_499_p2 = (7'd63 - sub_ln622_fu_395_p2);

assign sub_ln391_fu_427_p2 = (10'd511 - sub_ln621_fu_377_p2);

assign sub_ln414_14_fu_655_p2 = (10'd511 - sub_ln599_fu_593_p2);

assign sub_ln414_15_fu_1316_p2 = (7'd63 - sub_ln600_reg_1513);

assign sub_ln414_16_fu_721_p2 = (7'd63 - sub_ln600_fu_611_p2);

assign sub_ln414_fu_641_p2 = (10'd511 - sub_ln599_fu_593_p2);

assign sub_ln599_fu_593_p2 = ($signed(10'd512) - $signed(zext_ln599_fu_589_p1));

assign sub_ln600_fu_611_p2 = ($signed(7'd64) - $signed(zext_ln600_fu_607_p1));

assign sub_ln621_fu_377_p2 = ($signed(10'd512) - $signed(zext_ln621_fu_373_p1));

assign sub_ln622_fu_395_p2 = ($signed(7'd64) - $signed(zext_ln622_fu_391_p1));

assign sub_ln674_13_fu_1296_p2 = ($signed(7'd64) - $signed(zext_ln600_reg_1508));

assign sub_ln674_fu_617_p2 = ($signed(10'd512) - $signed(zext_ln599_fu_589_p1));

assign tmp_345_fu_473_p3 = sub_ln622_fu_395_p2[32'd6];

integer ap_tvar_int_0;

always @ (select_ln414_fu_1060_p3) begin
    for (ap_tvar_int_0 = 320 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 319 - 0) begin
            tmp_351_fu_1067_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            tmp_351_fu_1067_p4[ap_tvar_int_0] = select_ln414_fu_1060_p3[319 - ap_tvar_int_0];
        end
    end
end

assign tmp_352_fu_623_p3 = sub_ln599_fu_593_p2[32'd9];

integer ap_tvar_int_1;

always @ (shl_ln414_fu_1251_p2) begin
    for (ap_tvar_int_1 = 512 - 1; ap_tvar_int_1 >= 0; ap_tvar_int_1 = ap_tvar_int_1 - 1) begin
        if (ap_tvar_int_1 > 511 - 0) begin
            tmp_353_fu_1257_p4[ap_tvar_int_1] = 1'b0;
        end else begin
            tmp_353_fu_1257_p4[ap_tvar_int_1] = shl_ln414_fu_1251_p2[511 - ap_tvar_int_1];
        end
    end
end

assign tmp_354_fu_695_p3 = sub_ln600_fu_611_p2[32'd6];

integer ap_tvar_int_2;

always @ (shl_ln414_11_fu_1331_p2) begin
    for (ap_tvar_int_2 = 64 - 1; ap_tvar_int_2 >= 0; ap_tvar_int_2 = ap_tvar_int_2 - 1) begin
        if (ap_tvar_int_2 > 63 - 0) begin
            tmp_355_fu_1337_p4[ap_tvar_int_2] = 1'b0;
        end else begin
            tmp_355_fu_1337_p4[ap_tvar_int_2] = shl_ln414_11_fu_1331_p2[63 - ap_tvar_int_2];
        end
    end
end

assign tmp_356_fu_862_p1 = rxEng_dataBuffer3b_dout[319:0];

assign tmp_357_fu_1044_p1 = reg_336[319:0];

assign tmp_data_V_3_fu_545_p1 = rxEng_dataBuffer3b_dout[511:0];

assign tmp_data_V_fu_852_p1 = rxEng_dataBuffer3b_dout[511:0];

assign tmp_fu_401_p3 = sub_ln621_fu_377_p2[32'd9];

assign tmp_i_nbreadreq_fu_174_p3 = rxEng_optionalFieldsMetaFifo_empty_n;

assign tmp_syn_V_fu_844_p3 = rxEng_optionalFieldsMetaFifo_dout[32'd8];

assign trunc_ln145_fu_840_p1 = rxEng_optionalFieldsMetaFifo_dout[3:0];

assign trunc_ln414_fu_1048_p1 = reg_336[0:0];

assign xor_ln391_1_fu_539_p2 = (64'd18446744073709551615 ^ and_ln391_3_fu_533_p2);

assign xor_ln391_fu_467_p2 = (512'd13407807929942597099574024998205846127479365820592393377723561443721764030073546976801874298166903427690031858186486050853753882811946569946433649006084095 ^ and_ln391_fu_461_p2);

assign xor_ln414_5_fu_1274_p2 = (512'd13407807929942597099574024998205846127479365820592393377723561443721764030073546976801874298166903427690031858186486050853753882811946569946433649006084095 ^ and_ln414_28_reg_1535);

assign xor_ln414_6_fu_1354_p2 = (64'd18446744073709551615 ^ and_ln414_31_reg_1547);

assign xor_ln414_fu_1104_p2 = (320'd2135987035920910082395021706169552114602704522356652769947041607822219725780640550022962086936575 ^ and_ln414_fu_1098_p2);

assign xor_ln563_fu_884_p2 = (grp_fu_316_p3 ^ 1'd1);

assign xor_ln582_fu_1134_p2 = (parseHeader ^ 1'd1);

assign xor_ln874_fu_819_p2 = (icmp_ln870_79_fu_575_p2 ^ 1'd1);

assign zext_ln174_fu_1401_p1 = or_ln_fu_1393_p4;

assign zext_ln391_3_fu_441_p1 = select_ln391_fu_419_p3;

assign zext_ln391_4_fu_445_p1 = select_ln391_2_fu_433_p3;

assign zext_ln391_5_fu_481_p1 = tmp_345_fu_473_p3;

assign zext_ln391_6_fu_513_p1 = select_ln391_3_fu_491_p3;

assign zext_ln391_7_fu_517_p1 = select_ln391_4_fu_505_p3;

assign zext_ln391_fu_409_p1 = tmp_fu_401_p3;

assign zext_ln414_30_fu_1019_p1 = shl_ln4_reg_1443;

assign zext_ln414_31_fu_1175_p1 = shl_ln6_reg_1489;

assign zext_ln414_32_fu_1213_p1 = bvh_d_index_reg_1501;

assign zext_ln414_33_fu_631_p1 = tmp_352_fu_623_p3;

assign zext_ln414_34_fu_1247_p1 = select_ln414_25_fu_1242_p3;

assign zext_ln414_35_fu_669_p1 = select_ln414_24_fu_647_p3;

assign zext_ln414_36_fu_673_p1 = select_ln414_26_fu_661_p3;

assign zext_ln414_37_fu_703_p1 = tmp_354_fu_695_p3;

assign zext_ln414_38_fu_1327_p1 = select_ln414_29_fu_1321_p3;

assign zext_ln414_39_fu_735_p1 = select_ln414_28_fu_713_p3;

assign zext_ln414_40_fu_739_p1 = select_ln414_30_fu_727_p3;

assign zext_ln414_fu_981_p1 = shl_ln_reg_1436;

assign zext_ln563_fu_896_p1 = xor_ln563_fu_884_p2;

assign zext_ln599_fu_589_p1 = shl_ln6_fu_581_p3;

assign zext_ln600_fu_607_p1 = bvh_d_index_fu_599_p3;

assign zext_ln621_fu_373_p1 = shl_ln_fu_365_p3;

assign zext_ln622_fu_391_p1 = shl_ln4_fu_383_p3;

assign zext_ln674_19_fu_961_p1 = shl_ln_reg_1436;

assign zext_ln674_20_fu_996_p1 = shl_ln4_reg_1443;

assign zext_ln674_21_fu_999_p1 = shl_ln4_reg_1443;

assign zext_ln674_22_fu_1152_p1 = shl_ln6_reg_1489;

assign zext_ln674_23_fu_1155_p1 = shl_ln6_reg_1489;

assign zext_ln674_24_fu_1190_p1 = bvh_d_index_reg_1501;

assign zext_ln674_25_fu_1193_p1 = bvh_d_index_reg_1501;

assign zext_ln674_26_fu_1228_p1 = sub_ln674_reg_1519;

assign zext_ln674_27_fu_1301_p1 = sub_ln674_13_fu_1296_p2;

assign zext_ln674_fu_958_p1 = shl_ln_reg_1436;

assign zext_ln819_1_fu_761_p1 = bvh_d_index_fu_599_p3;

assign zext_ln819_2_fu_797_p1 = bvh_1_fu_789_p3;

assign zext_ln819_fu_909_p1 = bvh_fu_901_p3;

always @ (posedge ap_clk) begin
    shl_ln_reg_1436[4:0] <= 5'b00000;
    shl_ln4_reg_1443[1:0] <= 2'b00;
    shl_ln6_reg_1489[4:0] <= 5'b00000;
    sub_ln599_reg_1496[4:0] <= 5'b00000;
    bvh_d_index_reg_1501[1:0] <= 2'b00;
    zext_ln600_reg_1508[1:0] <= 2'b00;
    zext_ln600_reg_1508[6] <= 1'b0;
    sub_ln600_reg_1513[1:0] <= 2'b00;
    sub_ln674_reg_1519[4:0] <= 5'b00000;
    sub_ln414_reg_1530[4:0] <= 5'b11111;
end

endmodule //toe_top_drop_optional_header_fields_512_s
