// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module toe_top_prependPseudoHeader_512_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        rxEng_pseudoHeaderFifo_dout,
        rxEng_pseudoHeaderFifo_empty_n,
        rxEng_pseudoHeaderFifo_read,
        rxEng_dataBuffer5_dout,
        rxEng_dataBuffer5_empty_n,
        rxEng_dataBuffer5_read,
        rxEng_dataBuffer1_din,
        rxEng_dataBuffer1_full_n,
        rxEng_dataBuffer1_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [1023:0] rxEng_pseudoHeaderFifo_dout;
input   rxEng_pseudoHeaderFifo_empty_n;
output   rxEng_pseudoHeaderFifo_read;
input  [1023:0] rxEng_dataBuffer5_dout;
input   rxEng_dataBuffer5_empty_n;
output   rxEng_dataBuffer5_read;
output  [1023:0] rxEng_dataBuffer1_din;
input   rxEng_dataBuffer1_full_n;
output   rxEng_dataBuffer1_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg rxEng_pseudoHeaderFifo_read;
reg rxEng_dataBuffer5_read;
reg[1023:0] rxEng_dataBuffer1_din;
reg rxEng_dataBuffer1_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire   [0:0] tmp_i_nbreadreq_fu_48_p3;
reg    ap_predicate_op21_read_state1;
wire   [0:0] tmp_i_275_nbreadreq_fu_62_p3;
reg    ap_predicate_op31_read_state1;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] state_2_load_reg_192;
reg   [0:0] tmp_i_reg_199;
reg   [0:0] tmp_290_reg_208;
reg    ap_predicate_op43_write_state2;
reg   [0:0] tmp_i_275_reg_212;
reg    ap_predicate_op48_write_state2;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] state_2;
reg   [0:0] firstPayload;
reg   [95:0] prevWord_data_V_7;
reg    rxEng_pseudoHeaderFifo_blk_n;
wire    ap_block_pp0_stage0;
reg    rxEng_dataBuffer1_blk_n;
reg    rxEng_dataBuffer5_blk_n;
reg   [1023:0] rxEng_pseudoHeaderFifo_read_reg_203;
wire   [0:0] tmp_290_fu_110_p3;
wire   [511:0] tmp_data_V_fu_130_p1;
wire   [511:0] p_Result_s_fu_146_p5;
wire   [0:0] firstPayload_load_load_fu_96_p1;
reg   [64:0] tmp_reg_229;
reg    ap_block_pp0_stage0_subdone;
wire   [511:0] ap_phi_reg_pp0_iter0_sendWord_data_V_9_reg_83;
reg   [511:0] ap_phi_reg_pp0_iter1_sendWord_data_V_9_reg_83;
wire   [0:0] tmp_last_V_fu_134_p3;
wire   [95:0] trunc_ln145_fu_100_p1;
reg    ap_block_pp0_stage0_01001;
wire   [1023:0] zext_ln174_fu_187_p1;
wire   [576:0] tmp_s_fu_180_p3;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_137;
reg    ap_condition_151;
reg    ap_condition_98;
reg    ap_condition_154;
reg    ap_condition_175;
reg    ap_condition_158;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 state_2 = 1'd0;
#0 firstPayload = 1'd1;
#0 prevWord_data_V_7 = 96'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_98)) begin
        if ((1'b1 == ap_condition_151)) begin
            ap_phi_reg_pp0_iter1_sendWord_data_V_9_reg_83 <= tmp_data_V_fu_130_p1;
        end else if ((1'b1 == ap_condition_137)) begin
            ap_phi_reg_pp0_iter1_sendWord_data_V_9_reg_83 <= p_Result_s_fu_146_p5;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_sendWord_data_V_9_reg_83 <= ap_phi_reg_pp0_iter0_sendWord_data_V_9_reg_83;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_98)) begin
        if ((1'b1 == ap_condition_137)) begin
            firstPayload <= 1'd0;
        end else if ((1'b1 == ap_condition_154)) begin
            firstPayload <= 1'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_98)) begin
        if ((1'b1 == ap_condition_158)) begin
            state_2 <= 1'd0;
        end else if ((1'b1 == ap_condition_154)) begin
            state_2 <= 1'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_i_nbreadreq_fu_48_p3 == 1'd1) & (state_2 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        prevWord_data_V_7 <= trunc_ln145_fu_100_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op21_read_state1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        rxEng_pseudoHeaderFifo_read_reg_203 <= rxEng_pseudoHeaderFifo_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        state_2_load_reg_192 <= state_2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_i_nbreadreq_fu_48_p3 == 1'd1) & (state_2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_290_reg_208 <= rxEng_pseudoHeaderFifo_dout[32'd576];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (state_2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_i_275_reg_212 <= tmp_i_275_nbreadreq_fu_62_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (state_2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_i_reg_199 <= tmp_i_nbreadreq_fu_48_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_i_275_nbreadreq_fu_62_p3 == 1'd1) & (state_2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_reg_229 <= {{rxEng_dataBuffer5_dout[576:512]}};
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op48_write_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op43_write_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        rxEng_dataBuffer1_blk_n = rxEng_dataBuffer1_full_n;
    end else begin
        rxEng_dataBuffer1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_175)) begin
        if ((ap_predicate_op48_write_state2 == 1'b1)) begin
            rxEng_dataBuffer1_din = zext_ln174_fu_187_p1;
        end else if ((ap_predicate_op43_write_state2 == 1'b1)) begin
            rxEng_dataBuffer1_din = rxEng_pseudoHeaderFifo_read_reg_203;
        end else begin
            rxEng_dataBuffer1_din = 'bx;
        end
    end else begin
        rxEng_dataBuffer1_din = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op48_write_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op43_write_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        rxEng_dataBuffer1_write = 1'b1;
    end else begin
        rxEng_dataBuffer1_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op31_read_state1 == 1'b1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_done_reg == 1'b0))) begin
        rxEng_dataBuffer5_blk_n = rxEng_dataBuffer5_empty_n;
    end else begin
        rxEng_dataBuffer5_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op31_read_state1 == 1'b1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        rxEng_dataBuffer5_read = 1'b1;
    end else begin
        rxEng_dataBuffer5_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op21_read_state1 == 1'b1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_done_reg == 1'b0))) begin
        rxEng_pseudoHeaderFifo_blk_n = rxEng_pseudoHeaderFifo_empty_n;
    end else begin
        rxEng_pseudoHeaderFifo_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op21_read_state1 == 1'b1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        rxEng_pseudoHeaderFifo_read = 1'b1;
    end else begin
        rxEng_pseudoHeaderFifo_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((ap_predicate_op48_write_state2 == 1'b1) & (rxEng_dataBuffer1_full_n == 1'b0)) | ((ap_predicate_op43_write_state2 == 1'b1) & (rxEng_dataBuffer1_full_n == 1'b0)))) | ((ap_start == 1'b1) & ((ap_done_reg == 1'b1) | ((ap_predicate_op31_read_state1 == 1'b1) & (rxEng_dataBuffer5_empty_n == 1'b0)) | ((ap_predicate_op21_read_state1 == 1'b1) & (rxEng_pseudoHeaderFifo_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((ap_predicate_op48_write_state2 == 1'b1) & (rxEng_dataBuffer1_full_n == 1'b0)) | ((ap_predicate_op43_write_state2 == 1'b1) & (rxEng_dataBuffer1_full_n == 1'b0)))) | ((ap_start == 1'b1) & ((ap_done_reg == 1'b1) | ((ap_predicate_op31_read_state1 == 1'b1) & (rxEng_dataBuffer5_empty_n == 1'b0)) | ((ap_predicate_op21_read_state1 == 1'b1) & (rxEng_pseudoHeaderFifo_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((ap_predicate_op48_write_state2 == 1'b1) & (rxEng_dataBuffer1_full_n == 1'b0)) | ((ap_predicate_op43_write_state2 == 1'b1) & (rxEng_dataBuffer1_full_n == 1'b0)))) | ((ap_start == 1'b1) & ((ap_done_reg == 1'b1) | ((ap_predicate_op31_read_state1 == 1'b1) & (rxEng_dataBuffer5_empty_n == 1'b0)) | ((ap_predicate_op21_read_state1 == 1'b1) & (rxEng_pseudoHeaderFifo_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_done_reg == 1'b1) | ((ap_predicate_op31_read_state1 == 1'b1) & (rxEng_dataBuffer5_empty_n == 1'b0)) | ((ap_predicate_op21_read_state1 == 1'b1) & (rxEng_pseudoHeaderFifo_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (((ap_predicate_op48_write_state2 == 1'b1) & (rxEng_dataBuffer1_full_n == 1'b0)) | ((ap_predicate_op43_write_state2 == 1'b1) & (rxEng_dataBuffer1_full_n == 1'b0)));
end

always @ (*) begin
    ap_condition_137 = ((tmp_i_275_nbreadreq_fu_62_p3 == 1'd1) & (state_2 == 1'd1) & (firstPayload_load_load_fu_96_p1 == 1'd1));
end

always @ (*) begin
    ap_condition_151 = ((tmp_i_275_nbreadreq_fu_62_p3 == 1'd1) & (state_2 == 1'd1) & (firstPayload_load_load_fu_96_p1 == 1'd0));
end

always @ (*) begin
    ap_condition_154 = ((tmp_i_nbreadreq_fu_48_p3 == 1'd1) & (state_2 == 1'd0) & (tmp_290_fu_110_p3 == 1'd1));
end

always @ (*) begin
    ap_condition_158 = ((tmp_i_275_nbreadreq_fu_62_p3 == 1'd1) & (state_2 == 1'd1) & (tmp_last_V_fu_134_p3 == 1'd1));
end

always @ (*) begin
    ap_condition_175 = ((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_98 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_phi_reg_pp0_iter0_sendWord_data_V_9_reg_83 = 'bx;

always @ (*) begin
    ap_predicate_op21_read_state1 = ((tmp_i_nbreadreq_fu_48_p3 == 1'd1) & (state_2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op31_read_state1 = ((tmp_i_275_nbreadreq_fu_62_p3 == 1'd1) & (state_2 == 1'd1));
end

always @ (*) begin
    ap_predicate_op43_write_state2 = ((tmp_290_reg_208 == 1'd0) & (tmp_i_reg_199 == 1'd1) & (state_2_load_reg_192 == 1'd0));
end

always @ (*) begin
    ap_predicate_op48_write_state2 = ((tmp_i_275_reg_212 == 1'd1) & (state_2_load_reg_192 == 1'd1));
end

assign firstPayload_load_load_fu_96_p1 = firstPayload;

assign p_Result_s_fu_146_p5 = {{tmp_data_V_fu_130_p1[511:96]}, {prevWord_data_V_7}};

assign tmp_290_fu_110_p3 = rxEng_pseudoHeaderFifo_dout[32'd576];

assign tmp_data_V_fu_130_p1 = rxEng_dataBuffer5_dout[511:0];

assign tmp_i_275_nbreadreq_fu_62_p3 = rxEng_dataBuffer5_empty_n;

assign tmp_i_nbreadreq_fu_48_p3 = rxEng_pseudoHeaderFifo_empty_n;

assign tmp_last_V_fu_134_p3 = rxEng_dataBuffer5_dout[32'd576];

assign tmp_s_fu_180_p3 = {{tmp_reg_229}, {ap_phi_reg_pp0_iter1_sendWord_data_V_9_reg_83}};

assign trunc_ln145_fu_100_p1 = rxEng_pseudoHeaderFifo_dout[95:0];

assign zext_ln174_fu_187_p1 = tmp_s_fu_180_p3;

endmodule //toe_top_prependPseudoHeader_512_s
