// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module toe_top_read_data_arbiter_512_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        txApp2txEng_data_stream_dout,
        txApp2txEng_data_stream_empty_n,
        txApp2txEng_data_stream_read,
        txBufferReadDataStitched_dout,
        txBufferReadDataStitched_empty_n,
        txBufferReadDataStitched_read,
        txEng_isDDRbypass_dout,
        txEng_isDDRbypass_empty_n,
        txEng_isDDRbypass_read,
        txEng_tcpPkgBuffer0_din,
        txEng_tcpPkgBuffer0_full_n,
        txEng_tcpPkgBuffer0_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [1023:0] txApp2txEng_data_stream_dout;
input   txApp2txEng_data_stream_empty_n;
output   txApp2txEng_data_stream_read;
input  [1023:0] txBufferReadDataStitched_dout;
input   txBufferReadDataStitched_empty_n;
output   txBufferReadDataStitched_read;
input  [0:0] txEng_isDDRbypass_dout;
input   txEng_isDDRbypass_empty_n;
output   txEng_isDDRbypass_read;
output  [1023:0] txEng_tcpPkgBuffer0_din;
input   txEng_tcpPkgBuffer0_full_n;
output   txEng_tcpPkgBuffer0_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg txApp2txEng_data_stream_read;
reg txBufferReadDataStitched_read;
reg txEng_isDDRbypass_read;
reg[1023:0] txEng_tcpPkgBuffer0_din;
reg txEng_tcpPkgBuffer0_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire   [0:0] tmp_20_i_nbreadreq_fu_42_p3;
reg    ap_predicate_op24_read_state1;
wire   [0:0] tmp_i_271_nbreadreq_fu_56_p3;
reg    ap_predicate_op31_read_state1;
wire   [0:0] tmp_i_nbreadreq_fu_70_p3;
reg    ap_predicate_op38_read_state1;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [1:0] tps_state_V_load_reg_129;
reg   [0:0] tmp_20_i_reg_133;
reg    ap_predicate_op44_write_state2;
reg   [0:0] tmp_i_271_reg_145;
reg    ap_predicate_op45_write_state2;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
reg   [1:0] tps_state_V;
reg    txEng_isDDRbypass_blk_n;
wire    ap_block_pp0_stage0;
reg    txBufferReadDataStitched_blk_n;
reg    txEng_tcpPkgBuffer0_blk_n;
reg    txApp2txEng_data_stream_blk_n;
reg   [1023:0] txApp2txEng_data_stream_read_reg_137;
reg   [1023:0] txBufferReadDataStitched_read_reg_149;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] tmp_last_V_6_fu_101_p3;
wire   [0:0] tmp_last_V_fu_109_p3;
wire   [0:0] tmp_read_fu_78_p2;
reg    ap_block_pp0_stage0_01001;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_172;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 tps_state_V = 2'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_i_nbreadreq_fu_70_p3 == 1'd1) & (tps_state_V == 2'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_read_fu_78_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tps_state_V <= 2'd2;
    end else if (((tmp_i_nbreadreq_fu_70_p3 == 1'd1) & (tps_state_V == 2'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_read_fu_78_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tps_state_V <= 2'd1;
    end else if ((((tmp_i_271_nbreadreq_fu_56_p3 == 1'd1) & (tps_state_V == 2'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_last_V_fu_109_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_20_i_nbreadreq_fu_42_p3 == 1'd1) & (tps_state_V == 2'd2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_last_V_6_fu_101_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        tps_state_V <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tps_state_V == 2'd2) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_20_i_reg_133 <= tmp_20_i_nbreadreq_fu_42_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((tps_state_V == 2'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_i_271_reg_145 <= tmp_i_271_nbreadreq_fu_56_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tps_state_V_load_reg_129 <= tps_state_V;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_op24_read_state1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        txApp2txEng_data_stream_read_reg_137 <= txApp2txEng_data_stream_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_op31_read_state1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        txBufferReadDataStitched_read_reg_149 <= txBufferReadDataStitched_dout;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op24_read_state1 == 1'b1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_done_reg == 1'b0) & (1'b0 == ap_block_pp0_stage0))) begin
        txApp2txEng_data_stream_blk_n = txApp2txEng_data_stream_empty_n;
    end else begin
        txApp2txEng_data_stream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op24_read_state1 == 1'b1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        txApp2txEng_data_stream_read = 1'b1;
    end else begin
        txApp2txEng_data_stream_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op31_read_state1 == 1'b1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_done_reg == 1'b0) & (1'b0 == ap_block_pp0_stage0))) begin
        txBufferReadDataStitched_blk_n = txBufferReadDataStitched_empty_n;
    end else begin
        txBufferReadDataStitched_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op31_read_state1 == 1'b1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        txBufferReadDataStitched_read = 1'b1;
    end else begin
        txBufferReadDataStitched_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op38_read_state1 == 1'b1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_done_reg == 1'b0) & (1'b0 == ap_block_pp0_stage0))) begin
        txEng_isDDRbypass_blk_n = txEng_isDDRbypass_empty_n;
    end else begin
        txEng_isDDRbypass_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op38_read_state1 == 1'b1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        txEng_isDDRbypass_read = 1'b1;
    end else begin
        txEng_isDDRbypass_read = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_op45_write_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_predicate_op44_write_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)))) begin
        txEng_tcpPkgBuffer0_blk_n = txEng_tcpPkgBuffer0_full_n;
    end else begin
        txEng_tcpPkgBuffer0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_172)) begin
        if ((ap_predicate_op45_write_state2 == 1'b1)) begin
            txEng_tcpPkgBuffer0_din = txBufferReadDataStitched_read_reg_149;
        end else if ((ap_predicate_op44_write_state2 == 1'b1)) begin
            txEng_tcpPkgBuffer0_din = txApp2txEng_data_stream_read_reg_137;
        end else begin
            txEng_tcpPkgBuffer0_din = 'bx;
        end
    end else begin
        txEng_tcpPkgBuffer0_din = 'bx;
    end
end

always @ (*) begin
    if ((((ap_predicate_op45_write_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_predicate_op44_write_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        txEng_tcpPkgBuffer0_write = 1'b1;
    end else begin
        txEng_tcpPkgBuffer0_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & ((ap_done_reg == 1'b1) | ((ap_predicate_op38_read_state1 == 1'b1) & (txEng_isDDRbypass_empty_n == 1'b0)) | ((ap_predicate_op31_read_state1 == 1'b1) & (txBufferReadDataStitched_empty_n == 1'b0)) | ((ap_predicate_op24_read_state1 == 1'b1) & (txApp2txEng_data_stream_empty_n == 1'b0)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((ap_predicate_op45_write_state2 == 1'b1) & (txEng_tcpPkgBuffer0_full_n == 1'b0)) | ((ap_predicate_op44_write_state2 == 1'b1) & (txEng_tcpPkgBuffer0_full_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & ((ap_done_reg == 1'b1) | ((ap_predicate_op38_read_state1 == 1'b1) & (txEng_isDDRbypass_empty_n == 1'b0)) | ((ap_predicate_op31_read_state1 == 1'b1) & (txBufferReadDataStitched_empty_n == 1'b0)) | ((ap_predicate_op24_read_state1 == 1'b1) & (txApp2txEng_data_stream_empty_n == 1'b0)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((ap_predicate_op45_write_state2 == 1'b1) & (txEng_tcpPkgBuffer0_full_n == 1'b0)) | ((ap_predicate_op44_write_state2 == 1'b1) & (txEng_tcpPkgBuffer0_full_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & ((ap_done_reg == 1'b1) | ((ap_predicate_op38_read_state1 == 1'b1) & (txEng_isDDRbypass_empty_n == 1'b0)) | ((ap_predicate_op31_read_state1 == 1'b1) & (txBufferReadDataStitched_empty_n == 1'b0)) | ((ap_predicate_op24_read_state1 == 1'b1) & (txApp2txEng_data_stream_empty_n == 1'b0)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((ap_predicate_op45_write_state2 == 1'b1) & (txEng_tcpPkgBuffer0_full_n == 1'b0)) | ((ap_predicate_op44_write_state2 == 1'b1) & (txEng_tcpPkgBuffer0_full_n == 1'b0)))));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_done_reg == 1'b1) | ((ap_predicate_op38_read_state1 == 1'b1) & (txEng_isDDRbypass_empty_n == 1'b0)) | ((ap_predicate_op31_read_state1 == 1'b1) & (txBufferReadDataStitched_empty_n == 1'b0)) | ((ap_predicate_op24_read_state1 == 1'b1) & (txApp2txEng_data_stream_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (((ap_predicate_op45_write_state2 == 1'b1) & (txEng_tcpPkgBuffer0_full_n == 1'b0)) | ((ap_predicate_op44_write_state2 == 1'b1) & (txEng_tcpPkgBuffer0_full_n == 1'b0)));
end

always @ (*) begin
    ap_condition_172 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_01001));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

always @ (*) begin
    ap_predicate_op24_read_state1 = ((tmp_20_i_nbreadreq_fu_42_p3 == 1'd1) & (tps_state_V == 2'd2));
end

always @ (*) begin
    ap_predicate_op31_read_state1 = ((tmp_i_271_nbreadreq_fu_56_p3 == 1'd1) & (tps_state_V == 2'd1));
end

always @ (*) begin
    ap_predicate_op38_read_state1 = ((tmp_i_nbreadreq_fu_70_p3 == 1'd1) & (tps_state_V == 2'd0));
end

always @ (*) begin
    ap_predicate_op44_write_state2 = ((tmp_20_i_reg_133 == 1'd1) & (tps_state_V_load_reg_129 == 2'd2));
end

always @ (*) begin
    ap_predicate_op45_write_state2 = ((tmp_i_271_reg_145 == 1'd1) & (tps_state_V_load_reg_129 == 2'd1));
end

assign tmp_20_i_nbreadreq_fu_42_p3 = txApp2txEng_data_stream_empty_n;

assign tmp_i_271_nbreadreq_fu_56_p3 = txBufferReadDataStitched_empty_n;

assign tmp_i_nbreadreq_fu_70_p3 = txEng_isDDRbypass_empty_n;

assign tmp_last_V_6_fu_101_p3 = txApp2txEng_data_stream_dout[32'd576];

assign tmp_last_V_fu_109_p3 = txBufferReadDataStitched_dout[32'd576];

assign tmp_read_fu_78_p2 = txEng_isDDRbypass_dout;

endmodule //toe_top_read_data_arbiter_512_s
